[package]
name = "pwsh-sdk-ffi"
version = "0.18.0-bridge-v2.dbc.local.12"
edition = "2018"
license = "MIT/Apache-2.0"
publish = false
build = "build.rs"

[lib]
name = "multi_pwsh_sdk"
crate-type = ["cdylib"]

[dependencies]
pwsh-host = { path = "../pwsh-host" }

[build-dependencies]
winresource = "0.1"
