// <auto-generated />
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::delegate_loader::{AssemblyDelegateLoader, MethodWithUnknownSignature};
use crate::error::Error;
use crate::loader::get_assembly_delegate_loader;
use crate::pdcstr;
use crate::pdcstring::{PdCStr, PdCString};

pub type PowerShellHandle = *mut libc::c_void;

pub type FnPowerShellCreate = unsafe extern "system" fn() -> PowerShellHandle;

pub type FnPowerShellAddArgumentString =
    unsafe extern "system" fn(handle: PowerShellHandle, argument: *const libc::c_char);

pub type FnPowerShellAddParameterString =
    unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: *const libc::c_char);

pub type FnPowerShellAddParameterInt =
    unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: i32);

pub type FnPowerShellAddParameterLong =
    unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char, value: i64);

pub type FnPowerShellAddCommand = unsafe extern "system" fn(handle: PowerShellHandle, command: *const libc::c_char);

pub type FnPowerShellAddScript = unsafe extern "system" fn(handle: PowerShellHandle, script: *const libc::c_char);

pub type FnPowerShellAddStatement = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellInvoke = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellInvokeToUtf8 = unsafe extern "system" fn(
    handle: PowerShellHandle,
    buffer: *mut libc::c_uchar,
    buffer_len: i32,
    required_len: *mut i32,
) -> i32;

pub type FnPowerShellGetInvocationErrorCount = unsafe extern "system" fn(handle: PowerShellHandle) -> i32;

pub type FnPowerShellCopyInvocationErrorFieldToUtf8 = unsafe extern "system" fn(
    handle: PowerShellHandle,
    error_index: i32,
    field: i32,
    buffer: *mut libc::c_uchar,
    buffer_len: i32,
    required_len: *mut i32,
) -> i32;

pub type FnPowerShellClear = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShellExportToXml =
    unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnPowerShellExportToJson =
    unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnPowerShellExportToString =
    unsafe extern "system" fn(handle: PowerShellHandle, name: *const libc::c_char) -> *const libc::c_char;

pub type FnBindingsInvokeMemberJson = unsafe extern "system" fn(
    handle: PowerShellHandle,
    member_name: *const libc::c_char,
    arguments_json: *const libc::c_char,
) -> *const libc::c_char;

pub type FnBindingsGetPropertyJson =
    unsafe extern "system" fn(handle: PowerShellHandle, property_name: *const libc::c_char) -> *const libc::c_char;

pub type FnBindingsSetPropertyJson = unsafe extern "system" fn(
    handle: PowerShellHandle,
    property_name: *const libc::c_char,
    value_json: *const libc::c_char,
) -> *const libc::c_char;

pub type FnBindingsInvokeStaticMemberJson = unsafe extern "system" fn(
    member_name: *const libc::c_char,
    arguments_json: *const libc::c_char,
) -> *const libc::c_char;

pub type FnGCHandleFree = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnMarshalFreeCoTaskMem = unsafe extern "system" fn(ptr: *mut libc::c_void);

pub type FnPowerShell_Auto_AddCommand_String =
    unsafe extern "system" fn(handle: PowerShellHandle, cmdlet: *const libc::c_char) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddCommand_String_Bool = unsafe extern "system" fn(
    handle: PowerShellHandle,
    cmdlet: *const libc::c_char,
    useLocalScope: i32,
) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddParameter_String =
    unsafe extern "system" fn(handle: PowerShellHandle, parameterName: *const libc::c_char) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddScript_String =
    unsafe extern "system" fn(handle: PowerShellHandle, script: *const libc::c_char) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddScript_String_Bool = unsafe extern "system" fn(
    handle: PowerShellHandle,
    script: *const libc::c_char,
    useLocalScope: i32,
) -> PowerShellHandle;

pub type FnPowerShell_Auto_AddStatement_NoArgs =
    unsafe extern "system" fn(handle: PowerShellHandle) -> PowerShellHandle;

pub type FnPowerShell_Auto_CreateNestedPowerShell_NoArgs =
    unsafe extern "system" fn(handle: PowerShellHandle) -> PowerShellHandle;

pub type FnPowerShell_Auto_Dispose_NoArgs = unsafe extern "system" fn(handle: PowerShellHandle);

pub type FnPowerShell_Auto_Stop_NoArgs = unsafe extern "system" fn(handle: PowerShellHandle);

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ApiPs74 {
    pub create_fn: *const libc::c_void,
    pub add_argument_string_fn: *const libc::c_void,
    pub add_parameter_string_fn: *const libc::c_void,
    pub add_parameter_int_fn: *const libc::c_void,
    pub add_parameter_long_fn: *const libc::c_void,
    pub add_command_fn: *const libc::c_void,
    pub add_script_fn: *const libc::c_void,
    pub add_statement_fn: *const libc::c_void,
    pub invoke_fn: *const libc::c_void,
    pub invoke_to_utf8_fn: *const libc::c_void,
    pub get_invocation_error_count_fn: *const libc::c_void,
    pub copy_invocation_error_field_to_utf8_fn: *const libc::c_void,
    pub clear_fn: *const libc::c_void,
    pub export_to_xml_fn: *const libc::c_void,
    pub export_to_json_fn: *const libc::c_void,
    pub export_to_string_fn: *const libc::c_void,
    pub invoke_member_json_fn: *const libc::c_void,
    pub get_property_json_fn: *const libc::c_void,
    pub set_property_json_fn: *const libc::c_void,
    pub invoke_static_member_json_fn: *const libc::c_void,
    pub gc_handle_free_fn: *const libc::c_void,
    pub marshal_free_co_task_mem_fn: *const libc::c_void,
    pub power_shell_auto_add_command_string_fn: *const libc::c_void,
    pub power_shell_auto_add_command_string_bool_fn: *const libc::c_void,
    pub power_shell_auto_add_parameter_string_fn: *const libc::c_void,
    pub power_shell_auto_add_script_string_fn: *const libc::c_void,
    pub power_shell_auto_add_script_string_bool_fn: *const libc::c_void,
    pub power_shell_auto_add_statement_no_args_fn: *const libc::c_void,
    pub power_shell_auto_create_nested_power_shell_no_args_fn: *const libc::c_void,
    pub power_shell_auto_dispose_no_args_fn: *const libc::c_void,
    pub power_shell_auto_stop_no_args_fn: *const libc::c_void,
}

pub type FnBindingsGetApiPs74 = unsafe extern "system" fn() -> *const ApiPs74;

pub type FnBindingsGetAbiVersion = unsafe extern "system" fn() -> i32;

#[derive(Clone, Copy)]
pub struct Bindings {
    pub create_fn: FnPowerShellCreate,
    pub add_argument_string_fn: FnPowerShellAddArgumentString,
    pub add_parameter_string_fn: FnPowerShellAddParameterString,
    pub add_parameter_int_fn: FnPowerShellAddParameterInt,
    pub add_parameter_long_fn: FnPowerShellAddParameterLong,
    pub add_command_fn: FnPowerShellAddCommand,
    pub add_script_fn: FnPowerShellAddScript,
    pub add_statement_fn: FnPowerShellAddStatement,
    pub invoke_fn: FnPowerShellInvoke,
    pub invoke_to_utf8_fn: FnPowerShellInvokeToUtf8,
    pub get_invocation_error_count_fn: FnPowerShellGetInvocationErrorCount,
    pub copy_invocation_error_field_to_utf8_fn: FnPowerShellCopyInvocationErrorFieldToUtf8,
    pub clear_fn: FnPowerShellClear,
    pub export_to_xml_fn: FnPowerShellExportToXml,
    pub export_to_json_fn: FnPowerShellExportToJson,
    pub export_to_string_fn: FnPowerShellExportToString,
    pub invoke_member_json_fn: FnBindingsInvokeMemberJson,
    pub get_property_json_fn: FnBindingsGetPropertyJson,
    pub set_property_json_fn: FnBindingsSetPropertyJson,
    pub invoke_static_member_json_fn: FnBindingsInvokeStaticMemberJson,
    pub gc_handle_free_fn: FnGCHandleFree,
    pub marshal_free_co_task_mem_fn: FnMarshalFreeCoTaskMem,
    pub power_shell_auto_add_command_string_fn: FnPowerShell_Auto_AddCommand_String,
    pub power_shell_auto_add_command_string_bool_fn: FnPowerShell_Auto_AddCommand_String_Bool,
    pub power_shell_auto_add_parameter_string_fn: FnPowerShell_Auto_AddParameter_String,
    pub power_shell_auto_add_script_string_fn: FnPowerShell_Auto_AddScript_String,
    pub power_shell_auto_add_script_string_bool_fn: FnPowerShell_Auto_AddScript_String_Bool,
    pub power_shell_auto_add_statement_no_args_fn: FnPowerShell_Auto_AddStatement_NoArgs,
    pub power_shell_auto_create_nested_power_shell_no_args_fn: FnPowerShell_Auto_CreateNestedPowerShell_NoArgs,
    pub power_shell_auto_dispose_no_args_fn: FnPowerShell_Auto_Dispose_NoArgs,
    pub power_shell_auto_stop_no_args_fn: FnPowerShell_Auto_Stop_NoArgs,
}

impl Bindings {
    pub fn new() -> Result<Self, Error> {
        let fn_loader = get_assembly_delegate_loader();
        Self::new_with_loader(&fn_loader)
    }

    pub fn new_with_loader(fn_loader: &AssemblyDelegateLoader<PdCString>) -> Result<Self, Error> {
        fn get_function_pointer(
            fn_loader: &AssemblyDelegateLoader<PdCString>,
            type_name: impl AsRef<PdCStr>,
            method_name: impl AsRef<PdCStr>,
        ) -> Result<MethodWithUnknownSignature, Error> {
            fn_loader.get_function_pointer_for_unmanaged_callers_only_method(type_name, method_name)
        }

        let get_api_fn: FnBindingsGetApiPs74 = {
            let fn_ptr = get_function_pointer(
                fn_loader,
                pdcstr!("NativeHost.Bindings, Devolutions.PowerShell.SDK.Bindings"),
                pdcstr!("Bindings_GetApiPS74"),
            )?;
            unsafe { std::mem::transmute(fn_ptr) }
        };

        let get_abi_version_fn: FnBindingsGetAbiVersion = {
            let fn_ptr = get_function_pointer(
                fn_loader,
                pdcstr!("NativeHost.Bindings, Devolutions.PowerShell.SDK.Bindings"),
                pdcstr!("Bindings_GetAbiVersion"),
            )?;
            unsafe { std::mem::transmute(fn_ptr) }
        };
        if unsafe { get_abi_version_fn() } != 2 {
            return Err(Error::IO(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "unsupported managed PowerShell bindings ABI version",
            )));
        }

        let api = unsafe {
            let api_ptr = get_api_fn();
            assert!(!api_ptr.is_null());
            *api_ptr
        };

        Ok(Self {
            create_fn: unsafe { std::mem::transmute(api.create_fn) },
            add_argument_string_fn: unsafe { std::mem::transmute(api.add_argument_string_fn) },
            add_parameter_string_fn: unsafe { std::mem::transmute(api.add_parameter_string_fn) },
            add_parameter_int_fn: unsafe { std::mem::transmute(api.add_parameter_int_fn) },
            add_parameter_long_fn: unsafe { std::mem::transmute(api.add_parameter_long_fn) },
            add_command_fn: unsafe { std::mem::transmute(api.add_command_fn) },
            add_script_fn: unsafe { std::mem::transmute(api.add_script_fn) },
            add_statement_fn: unsafe { std::mem::transmute(api.add_statement_fn) },
            invoke_fn: unsafe { std::mem::transmute(api.invoke_fn) },
            invoke_to_utf8_fn: unsafe { std::mem::transmute(api.invoke_to_utf8_fn) },
            get_invocation_error_count_fn: unsafe { std::mem::transmute(api.get_invocation_error_count_fn) },
            copy_invocation_error_field_to_utf8_fn: unsafe {
                std::mem::transmute(api.copy_invocation_error_field_to_utf8_fn)
            },
            clear_fn: unsafe { std::mem::transmute(api.clear_fn) },
            export_to_xml_fn: unsafe { std::mem::transmute(api.export_to_xml_fn) },
            export_to_json_fn: unsafe { std::mem::transmute(api.export_to_json_fn) },
            export_to_string_fn: unsafe { std::mem::transmute(api.export_to_string_fn) },
            invoke_member_json_fn: unsafe { std::mem::transmute(api.invoke_member_json_fn) },
            get_property_json_fn: unsafe { std::mem::transmute(api.get_property_json_fn) },
            set_property_json_fn: unsafe { std::mem::transmute(api.set_property_json_fn) },
            invoke_static_member_json_fn: unsafe { std::mem::transmute(api.invoke_static_member_json_fn) },
            gc_handle_free_fn: unsafe { std::mem::transmute(api.gc_handle_free_fn) },
            marshal_free_co_task_mem_fn: unsafe { std::mem::transmute(api.marshal_free_co_task_mem_fn) },
            power_shell_auto_add_command_string_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_add_command_string_fn)
            },
            power_shell_auto_add_command_string_bool_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_add_command_string_bool_fn)
            },
            power_shell_auto_add_parameter_string_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_add_parameter_string_fn)
            },
            power_shell_auto_add_script_string_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_add_script_string_fn)
            },
            power_shell_auto_add_script_string_bool_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_add_script_string_bool_fn)
            },
            power_shell_auto_add_statement_no_args_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_add_statement_no_args_fn)
            },
            power_shell_auto_create_nested_power_shell_no_args_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_create_nested_power_shell_no_args_fn)
            },
            power_shell_auto_dispose_no_args_fn: unsafe {
                std::mem::transmute(api.power_shell_auto_dispose_no_args_fn)
            },
            power_shell_auto_stop_no_args_fn: unsafe { std::mem::transmute(api.power_shell_auto_stop_no_args_fn) },
        })
    }
}
