<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MultiPwshAppHostEnabled Condition="'$(MultiPwshAppHostEnabled)' == ''">false</MultiPwshAppHostEnabled>
    <MultiPwshAppHostCopyToOutput Condition="'$(MultiPwshAppHostCopyToOutput)' == ''">true</MultiPwshAppHostCopyToOutput>
    <MultiPwshAppHostCopyToPublish Condition="'$(MultiPwshAppHostCopyToPublish)' == ''">true</MultiPwshAppHostCopyToPublish>
    <MultiPwshRuntimeNativeContentCopyEnabled Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == ''">true</MultiPwshRuntimeNativeContentCopyEnabled>
    <MultiPwshAppHostPackageRoot Condition="'$(MultiPwshAppHostPackageRoot)' == ''">$(MSBuildThisFileDirectory)..\</MultiPwshAppHostPackageRoot>
    <MultiPwshAppHostRuntimeNativeRoot Condition="'$(MultiPwshAppHostRuntimeNativeRoot)' == ''">$(MultiPwshAppHostPackageRoot)runtimes\</MultiPwshAppHostRuntimeNativeRoot>
    <MultiPwshAppHostManifestPath Condition="'$(MultiPwshAppHostManifestPath)' == ''">$(MultiPwshAppHostPackageRoot)build\Devolutions.MultiPwsh.Cli.AppHostManifest.json</MultiPwshAppHostManifestPath>
    <MultiPwshAppHostSupportedRuntimeIdentifiers Condition="'$(MultiPwshAppHostSupportedRuntimeIdentifiers)' == ''">win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64</MultiPwshAppHostSupportedRuntimeIdentifiers>
  </PropertyGroup>
</Project>
