<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MultiPwshRuntimeNativeContentCopyEnabled Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == ''">true</MultiPwshRuntimeNativeContentCopyEnabled>
  </PropertyGroup>

  <ItemGroup Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == 'true' And ('$(RuntimeIdentifier)' == '' Or '$(RuntimeIdentifier)' == 'win-x64')">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\win-x64\native\multi-pwsh.exe" Condition="Exists('$(MSBuildThisFileDirectory)..\runtimes\win-x64\native\multi-pwsh.exe')">
      <Link>runtimes\win-x64\native\multi-pwsh.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <PublishState>Included</PublishState>
      <Visible>false</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == 'true' And ('$(RuntimeIdentifier)' == '' Or '$(RuntimeIdentifier)' == 'win-arm64')">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\win-arm64\native\multi-pwsh.exe" Condition="Exists('$(MSBuildThisFileDirectory)..\runtimes\win-arm64\native\multi-pwsh.exe')">
      <Link>runtimes\win-arm64\native\multi-pwsh.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <PublishState>Included</PublishState>
      <Visible>false</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == 'true' And ('$(RuntimeIdentifier)' == '' Or '$(RuntimeIdentifier)' == 'linux-x64')">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\linux-x64\native\multi-pwsh" Condition="Exists('$(MSBuildThisFileDirectory)..\runtimes\linux-x64\native\multi-pwsh')">
      <Link>runtimes\linux-x64\native\multi-pwsh</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <PublishState>Included</PublishState>
      <Visible>false</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == 'true' And ('$(RuntimeIdentifier)' == '' Or '$(RuntimeIdentifier)' == 'linux-arm64')">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\linux-arm64\native\multi-pwsh" Condition="Exists('$(MSBuildThisFileDirectory)..\runtimes\linux-arm64\native\multi-pwsh')">
      <Link>runtimes\linux-arm64\native\multi-pwsh</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <PublishState>Included</PublishState>
      <Visible>false</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == 'true' And ('$(RuntimeIdentifier)' == '' Or '$(RuntimeIdentifier)' == 'osx-x64')">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\osx-x64\native\multi-pwsh" Condition="Exists('$(MSBuildThisFileDirectory)..\runtimes\osx-x64\native\multi-pwsh')">
      <Link>runtimes\osx-x64\native\multi-pwsh</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <PublishState>Included</PublishState>
      <Visible>false</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(MultiPwshRuntimeNativeContentCopyEnabled)' == 'true' And ('$(RuntimeIdentifier)' == '' Or '$(RuntimeIdentifier)' == 'osx-arm64')">
    <Content Include="$(MSBuildThisFileDirectory)..\runtimes\osx-arm64\native\multi-pwsh" Condition="Exists('$(MSBuildThisFileDirectory)..\runtimes\osx-arm64\native\multi-pwsh')">
      <Link>runtimes\osx-arm64\native\multi-pwsh</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <PublishState>Included</PublishState>
      <Visible>false</Visible>
      <Pack>false</Pack>
    </Content>
  </ItemGroup>
</Project>
