// <auto-generated />
using System;
using System.Runtime.InteropServices;

namespace NativeHost
{
    public static partial class Bindings
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct ApiPS74
        {
            public IntPtr PowerShell_Create;
            public IntPtr PowerShell_AddArgument_String;
            public IntPtr PowerShell_AddParameter_String;
            public IntPtr PowerShell_AddParameter_Int;
            public IntPtr PowerShell_AddParameter_Long;
            public IntPtr PowerShell_AddCommand;
            public IntPtr PowerShell_AddScript;
            public IntPtr PowerShell_AddStatement;
            public IntPtr PowerShell_Invoke;
            public IntPtr PowerShell_InvokeToUtf8;
            public IntPtr PowerShell_GetInvocationErrorCount;
            public IntPtr PowerShell_CopyInvocationErrorFieldToUtf8;
            public IntPtr PowerShell_Clear;
            public IntPtr PowerShell_ExportToXml;
            public IntPtr PowerShell_ExportToJson;
            public IntPtr PowerShell_ExportToString;
            public IntPtr Bindings_InvokeMemberJson;
            public IntPtr Bindings_GetPropertyJson;
            public IntPtr Bindings_SetPropertyJson;
            public IntPtr Bindings_InvokeStaticMemberJson;
            public IntPtr GCHandle_Free;
            public IntPtr Marshal_FreeCoTaskMem;
            public IntPtr PowerShell_Auto_AddCommand_String;
            public IntPtr PowerShell_Auto_AddCommand_String_Bool;
            public IntPtr PowerShell_Auto_AddParameter_String;
            public IntPtr PowerShell_Auto_AddScript_String;
            public IntPtr PowerShell_Auto_AddScript_String_Bool;
            public IntPtr PowerShell_Auto_AddStatement_NoArgs;
            public IntPtr PowerShell_Auto_CreateNestedPowerShell_NoArgs;
            public IntPtr PowerShell_Auto_Dispose_NoArgs;
            public IntPtr PowerShell_Auto_Stop_NoArgs;
        }

        private static readonly object ApiPS74Lock = new object();
        private static IntPtr ApiPS74Ptr = IntPtr.Zero;

        [UnmanagedCallersOnly]
        public static IntPtr Bindings_GetApiPS74()
        {
            lock (ApiPS74Lock)
            {
                if (ApiPS74Ptr == IntPtr.Zero)
                {
                    ApiPS74 api = CreateApiPS74();
                    ApiPS74Ptr = Marshal.AllocCoTaskMem(Marshal.SizeOf<ApiPS74>());
                    Marshal.StructureToPtr(api, ApiPS74Ptr, false);
                }

                return ApiPS74Ptr;
            }
        }

        private static unsafe ApiPS74 CreateApiPS74()
        {
            return new ApiPS74
            {
                PowerShell_Create = (IntPtr)(delegate* unmanaged<IntPtr>)&PowerShell_Create,
                PowerShell_AddArgument_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, void>)&PowerShell_AddArgument_String,
                PowerShell_AddParameter_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr, void>)&PowerShell_AddParameter_String,
                PowerShell_AddParameter_Int = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, int, void>)&PowerShell_AddParameter_Int,
                PowerShell_AddParameter_Long = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, long, void>)&PowerShell_AddParameter_Long,
                PowerShell_AddCommand = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, void>)&PowerShell_AddCommand,
                PowerShell_AddScript = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, void>)&PowerShell_AddScript,
                PowerShell_AddStatement = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_AddStatement,
                PowerShell_Invoke = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_Invoke,
                PowerShell_InvokeToUtf8 = (IntPtr)(delegate* unmanaged<IntPtr, byte*, int, int*, int>)&PowerShell_InvokeToUtf8,
                PowerShell_GetInvocationErrorCount = (IntPtr)(delegate* unmanaged<IntPtr, int>)&PowerShell_GetInvocationErrorCount,
                PowerShell_CopyInvocationErrorFieldToUtf8 = (IntPtr)(delegate* unmanaged<IntPtr, int, int, byte*, int, int*, int>)&PowerShell_CopyInvocationErrorFieldToUtf8,
                PowerShell_Clear = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_Clear,
                PowerShell_ExportToXml = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_ExportToXml,
                PowerShell_ExportToJson = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_ExportToJson,
                PowerShell_ExportToString = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_ExportToString,
                Bindings_InvokeMemberJson = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr, IntPtr>)&Bindings_InvokeMemberJson,
                Bindings_GetPropertyJson = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&Bindings_GetPropertyJson,
                Bindings_SetPropertyJson = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr, IntPtr>)&Bindings_SetPropertyJson,
                Bindings_InvokeStaticMemberJson = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&Bindings_InvokeStaticMemberJson,
                GCHandle_Free = (IntPtr)(delegate* unmanaged<IntPtr, void>)&GCHandle_Free,
                Marshal_FreeCoTaskMem = (IntPtr)(delegate* unmanaged<IntPtr, void>)&Marshal_FreeCoTaskMem,
                PowerShell_Auto_AddCommand_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_Auto_AddCommand_String,
                PowerShell_Auto_AddCommand_String_Bool = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, int, IntPtr>)&PowerShell_Auto_AddCommand_String_Bool,
                PowerShell_Auto_AddParameter_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_Auto_AddParameter_String,
                PowerShell_Auto_AddScript_String = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, IntPtr>)&PowerShell_Auto_AddScript_String,
                PowerShell_Auto_AddScript_String_Bool = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr, int, IntPtr>)&PowerShell_Auto_AddScript_String_Bool,
                PowerShell_Auto_AddStatement_NoArgs = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr>)&PowerShell_Auto_AddStatement_NoArgs,
                PowerShell_Auto_CreateNestedPowerShell_NoArgs = (IntPtr)(delegate* unmanaged<IntPtr, IntPtr>)&PowerShell_Auto_CreateNestedPowerShell_NoArgs,
                PowerShell_Auto_Dispose_NoArgs = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_Auto_Dispose_NoArgs,
                PowerShell_Auto_Stop_NoArgs = (IntPtr)(delegate* unmanaged<IntPtr, void>)&PowerShell_Auto_Stop_NoArgs,
            };
        }
    }
}
