#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Devolutions.MultiPwsh.LiveContract.Generator;

/// <summary>
/// The closed Bridge Contract v2 compiler. It is a second, independent generator
/// beside <see cref="LiveContractGenerator"/>: the v1 preview keeps its exact
/// behaviour, and a compilation declares one root family or the other.
/// </summary>
[Generator]
public sealed class BridgeContractGenerator : IIncrementalGenerator
{
    private const string LiveContractAttribute = "Devolutions.PowerShell.Ffi.LiveObjects.LiveContractAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InterfaceDeclarationSyntax { AttributeLists.Count: > 0 }
                    or EnumDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntax, _) => syntax.SemanticModel.GetDeclaredSymbol(syntax.Node) as INamedTypeSymbol)
            .Where(static type => type is not null)!;

        IncrementalValueProvider<string> mode = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
                options.GlobalOptions.TryGetValue("build_property.LiveContractMode", out string? value) ? value : string.Empty);

        context.RegisterSourceOutput(
            declarations.Collect().Combine(mode).Combine(context.CompilationProvider),
            static (production, pair) =>
        {
            (System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> collected, string selectedMode) = pair.Left;
            Compilation compilation = pair.Right;
            List<INamedTypeSymbol> types = collected
                .GroupBy(static type => type, SymbolEqualityComparer.Default)
                .Select(static group => group.First())
                .ToList();
            List<INamedTypeSymbol> roots = types
                .Where(static type => BridgeContractAnalyzer.HasAttribute(type, BridgeContractAnalyzer.ContractAttribute))
                .ToList();

            // Referencing the SDK must never turn an ordinary consumer, or a v1
            // consumer, into diagnostics.
            if (roots.Count == 0)
            {
                return;
            }

            if (roots.Count != 1)
            {
                foreach (INamedTypeSymbol root in roots)
                {
                    production.ReportDiagnostic(Diagnostic.Create(
                        BridgeContractDiagnostics.InvalidContract,
                        BridgeContractAnalyzer.Location(root),
                        root.Name,
                        "exactly one [BridgeContract] root is allowed per compilation"));
                }

                return;
            }

            if (types.Any(static type => BridgeContractAnalyzer.HasAttribute(type, LiveContractAttribute)))
            {
                production.ReportDiagnostic(Diagnostic.Create(
                    BridgeContractDiagnostics.InvalidContract,
                    BridgeContractAnalyzer.Location(roots[0]),
                    roots[0].Name,
                    "a compilation declares either a v1 [LiveContract] root or a v2 [BridgeContract] root, never both"));
                return;
            }

            if (selectedMode is not ("Host" or "Payload"))
            {
                production.ReportDiagnostic(Diagnostic.Create(
                    BridgeContractDiagnostics.MissingMode,
                    BridgeContractAnalyzer.Location(roots[0])));
                return;
            }

            var diagnostics = new List<Diagnostic>();
            BridgeContractModel? contract = BridgeContractAnalyzer.Analyze(roots[0], types, compilation, diagnostics);
            foreach (Diagnostic diagnostic in diagnostics)
            {
                production.ReportDiagnostic(diagnostic);
            }

            if (contract is null)
            {
                return;
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            source.AppendLine("using System;");
            if (contract.Namespace.Length != 0)
            {
                source.Append("namespace ").Append(contract.Namespace).AppendLine(";");
                source.AppendLine();
            }

            EmitShared(source, contract, selectedMode);
            BridgeContractDataEmitter.Emit(source, contract);
            if (selectedMode == "Payload")
            {
                BridgeContractPayloadEmitter.Emit(source, contract);
            }
            else
            {
                BridgeContractHostEmitter.Emit(source, contract);
            }

            production.AddSource(
                $"{contract.Root.Name}.Bridge.{selectedMode}.g.cs",
                SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static void EmitShared(StringBuilder source, BridgeContractModel contract, string mode)
    {
        string name = BridgeNames.Contract(contract);
        source.Append("internal static class ").Append(name).AppendLine();
        source.AppendLine("{");
        source.Append("    internal const string ContractId = \"").Append(BridgeNames.Escape(contract.ContractId)).AppendLine("\";");
        source.Append("    internal const int MajorVersion = ").Append(Number(contract.MajorVersion)).AppendLine(";");
        source.Append("    internal const int MinorVersion = ").Append(Number(contract.MinorVersion)).AppendLine(";");
        source.Append("    internal const string TransportInterfaceId = \"").Append(contract.TransportInterfaceId).AppendLine("\";");
        source.Append("    internal const string Mode = \"").Append(mode).AppendLine("\";");
        source.Append("    internal const string DescriptorHashHex = \"")
            .Append(BridgeContractDescriptor.ToHex(contract.DescriptorHash)).AppendLine("\";");
        source.AppendLine("    internal const int DescriptorHashBytes = 32;");
        source.AppendLine();
        EmitBlob(source, "Descriptor", contract.Descriptor);
        EmitBlob(source, "DescriptorHash", contract.DescriptorHash);
        source.AppendLine();

        foreach (BridgeObjectModel model in contract.Objects)
        {
            source.Append("    internal const ulong Object").Append(Number(model.Id)).Append(" = ")
                .Append(Number(model.Id)).AppendLine("UL;");
            source.Append("    internal const uint Release").Append(Number(model.Id)).Append(" = ")
                .Append(Number(model.ReleaseId)).AppendLine("U;");
            foreach (BridgeMemberModel member in model.Members)
            {
                source.Append("    internal const uint Member").Append(Number(member.Ordinal)).Append(" = ")
                    .Append(Number(member.Ordinal)).AppendLine("U;");
            }
        }

        source.AppendLine();
        source.AppendLine("    internal static readonly global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellBridgeMemberEntry[] Members =");
        source.AppendLine("    [");
        foreach (BridgeObjectModel model in contract.Objects)
        {
            foreach (BridgeMemberModel member in model.Members)
            {
                source.Append("        new(")
                    .Append(Number(model.Id)).Append("UL, ")
                    .Append(Number(member.Ordinal)).Append("U, ")
                    .Append("global::Devolutions.PowerShell.Ffi.LiveObjects.BridgeMemberKind.").Append(member.Kind).Append(", ")
                    .Append("(global::Devolutions.PowerShell.Ffi.LiveObjects.BridgeMutation)").Append(Number(member.Mutation)).Append(", ")
                    .Append("(global::Devolutions.PowerShell.Ffi.LiveObjects.BridgePermission)").Append(Number(member.Permission)).Append(", ")
                    .Append(Number(member.Parameters.Count)).Append(", ")
                    .Append(Number(member.Result.Tag)).Append(", ")
                    .Append(Number(member.OrderingKey)).Append("UL, ")
                    .Append(Number(member.MaximumRequestBytes(contract.DataById))).Append(", ")
                    .Append(Number(member.MaximumReplyBytes(contract.DataById))).AppendLine("),");
            }
        }

        source.AppendLine("    ];");
        source.AppendLine();
        source.AppendLine("    /// <summary>Resolves a member without reflection, a dictionary, or a member name.</summary>");
        source.AppendLine("    internal static bool TryGetMember(ulong objectTypeId, uint ordinal, out global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellBridgeMemberEntry entry)");
        source.AppendLine("    {");
        source.AppendLine("        switch (objectTypeId)");
        source.AppendLine("        {");
        int index = 0;
        foreach (BridgeObjectModel model in contract.Objects)
        {
            source.Append("            case ").Append(Number(model.Id)).AppendLine("UL:");
            source.AppendLine("                switch (ordinal)");
            source.AppendLine("                {");
            foreach (BridgeMemberModel member in model.Members)
            {
                source.Append("                    case ").Append(Number(member.Ordinal)).Append("U: entry = Members[")
                    .Append(Number(index)).AppendLine("]; return true;");
                index++;
            }

            source.AppendLine("                    default: break;");
            source.AppendLine("                }");
            source.AppendLine();
            source.AppendLine("                break;");
        }

        source.AppendLine("            default: break;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        entry = default;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    /// <summary>Resolves a member from its globally unique ordinal alone, before any lease lookup.</summary>");
        source.AppendLine("    internal static bool TryGetMemberByOrdinal(uint ordinal, out global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellBridgeMemberEntry entry)");
        source.AppendLine("    {");
        source.AppendLine("        switch (ordinal)");
        source.AppendLine("        {");
        index = 0;
        foreach (BridgeObjectModel model in contract.Objects)
        {
            foreach (BridgeMemberModel member in model.Members)
            {
                source.Append("            case ").Append(Number(member.Ordinal)).Append("U: entry = Members[")
                    .Append(Number(index)).AppendLine("]; return true;");
                index++;
            }
        }

        source.AppendLine("            default: entry = default; return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    /// <summary>Resolves the object type whose declared release ordinal this is.</summary>");
        source.AppendLine("    internal static bool TryGetReleaseObjectType(uint ordinal, out ulong objectTypeId)");
        source.AppendLine("    {");
        source.AppendLine("        switch (ordinal)");
        source.AppendLine("        {");
        foreach (BridgeObjectModel model in contract.Objects)
        {
            source.Append("            case ").Append(Number(model.ReleaseId)).Append("U: objectTypeId = ")
                .Append(Number(model.Id)).AppendLine("UL; return true;");
        }

        source.AppendLine("            default: objectTypeId = 0UL; return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    /// <summary>Resolves the declared release ordinal for one object type.</summary>");
        source.AppendLine("    internal static bool TryGetReleaseOrdinal(ulong objectTypeId, out uint ordinal)");
        source.AppendLine("    {");
        source.AppendLine("        switch (objectTypeId)");
        source.AppendLine("        {");
        foreach (BridgeObjectModel model in contract.Objects)
        {
            source.Append("            case ").Append(Number(model.Id)).Append("UL: ordinal = ")
                .Append(Number(model.ReleaseId)).AppendLine("U; return true;");
        }

        source.AppendLine("            default: ordinal = 0U; return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void EmitBlob(StringBuilder source, string name, IReadOnlyList<byte> value)
    {
        source.Append("    internal static global::System.ReadOnlySpan<byte> ").Append(name).AppendLine(" => new byte[]");
        source.AppendLine("    {");
        for (int index = 0; index < value.Count; index += 16)
        {
            source.Append("        ");
            for (int offset = index; offset < value.Count && offset < index + 16; offset++)
            {
                source.Append("0x").Append(value[offset].ToString("X2", CultureInfo.InvariantCulture)).Append(", ");
            }

            source.AppendLine();
        }

        source.AppendLine("    };");
    }

    private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

    private static string Number(uint value) => value.ToString(CultureInfo.InvariantCulture);

    private static string Number(ulong value) => value.ToString(CultureInfo.InvariantCulture);

    private static string Number(byte value) => value.ToString(CultureInfo.InvariantCulture);
}

/// <summary>Deterministic generated-type naming shared by every emitter.</summary>
internal static class BridgeNames
{
    internal static string Contract(BridgeContractModel contract) => Prefix(contract.Root) + "Contract";

    internal static string Client(BridgeContractModel contract) => Prefix(contract.Root) + "Client";

    internal static string Binding(BridgeContractModel contract) => Prefix(contract.Root) + "BridgeBinding";

    internal static string Wrapper(BridgeObjectModel model) => Prefix(model.Symbol) + "Bridge";

    internal static string Value(BridgeDataModel model) => Prefix(model.Symbol) + "Value";

    internal static string Handler(BridgeObjectModel model) => "I" + Prefix(model.Symbol) + "BridgeHandler";

    internal static string Codec(BridgeContractModel contract) => Prefix(contract.Root) + "Codec";

    internal static string Prefix(INamedTypeSymbol type) =>
        Identifier(type.Name.Length > 1 && type.Name[0] == 'I' && char.IsUpper(type.Name[1])
            ? type.Name.Substring(1)
            : type.Name);

    internal static string Identifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    internal static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
