#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Devolutions.MultiPwsh.LiveContract.Generator;

[Generator]
public sealed class LiveContractGenerator : IIncrementalGenerator
{
    private const int MaximumWireBytes = 256;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntax, _) => (INamedTypeSymbol)syntax.SemanticModel.GetDeclaredSymbol(syntax.Node)!)
            .Where(static type => HasAttribute(type, "LiveContractAttribute") || HasAttribute(type, "LiveObjectAttribute"));

        IncrementalValueProvider<string> mode = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => options.GlobalOptions.TryGetValue("build_property.LiveContractMode", out string? value) ? value : string.Empty);

        context.RegisterSourceOutput(declarations.Collect().Combine(mode), static (production, pair) =>
        {
            List<INamedTypeSymbol> types = pair.Left
                .GroupBy(static type => type, SymbolEqualityComparer.Default)
                .Select(static group => group.First())
                .ToList();
            List<INamedTypeSymbol> roots = types.Where(static type => HasAttribute(type, "LiveContractAttribute")).ToList();

            // A reference to the SDK attributes must not turn ordinary consumers into
            // diagnostics merely because they do not declare a generated contract.
            if (roots.Count == 0)
            {
                return;
            }

            if (roots.Count != 1)
            {
                foreach (INamedTypeSymbol root in roots)
                {
                    production.ReportDiagnostic(Diagnostic.Create(InvalidContract, GetLocation(root), root.Name,
                        "exactly one [LiveContract] root is allowed per compilation"));
                }

                return;
            }

            if (pair.Right is not ("Host" or "Payload"))
            {
                production.ReportDiagnostic(Diagnostic.Create(MissingMode, GetLocation(roots[0])));
                return;
            }

            var diagnostics = new List<Diagnostic>();
            ContractInfo? contract = Analyze(roots[0], types, diagnostics);
            foreach (Diagnostic diagnostic in diagnostics)
            {
                production.ReportDiagnostic(diagnostic);
            }

            if (contract is null)
            {
                return;
            }

            StringBuilder source = new();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");
            if (!string.IsNullOrEmpty(contract.Namespace))
            {
                source.Append("namespace ").Append(contract.Namespace).AppendLine(";");
                source.AppendLine();
            }
            EmitConstants(source, contract, pair.Right);
            if (pair.Right == "Host")
            {
                EmitHost(source, contract);
            }
            else
            {
                EmitPayload(source, contract);
            }

            production.AddSource($"{contract.Root.Name}.{pair.Right}.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static ContractInfo? Analyze(INamedTypeSymbol root, List<INamedTypeSymbol> types, List<Diagnostic> diagnostics)
    {
        bool valid = true;
        AttributeData? contractAttribute = GetAttribute(root, "LiveContractAttribute");
        if (contractAttribute is null ||
            contractAttribute.ConstructorArguments.Length != 4 ||
            contractAttribute.ConstructorArguments[0].Value is not string contractId ||
            string.IsNullOrWhiteSpace(contractId) ||
            contractAttribute.ConstructorArguments[1].Value is not int major ||
            major <= 0 ||
            contractAttribute.ConstructorArguments[2].Value is not int minor ||
            minor < 0 ||
            contractAttribute.ConstructorArguments[3].Value is not string interfaceId ||
            !Guid.TryParse(interfaceId, out Guid parsedInterfaceId) ||
            parsedInterfaceId == Guid.Empty)
        {
            diagnostics.Add(Diagnostic.Create(InvalidContract, GetLocation(root), root.Name,
                "a stable contract ID, positive major version, non-negative minor version, and non-empty interface IID are required"));
            return null;
        }

        if (root.ContainingType is not null)
        {
            diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(root), root.Name, "nested interfaces are not supported"));
            valid = false;
        }

        List<ObjectInfo> objects = new();
        var objectIds = new HashSet<ulong>();
        foreach (INamedTypeSymbol type in types.Where(static type => HasAttribute(type, "LiveObjectAttribute")))
        {
            AttributeData? objectAttribute = GetAttribute(type, "LiveObjectAttribute");
            if (type.ContainingType is not null)
            {
                diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(type), type.Name, "nested interfaces are not supported"));
                valid = false;
            }

            if (type.TypeParameters.Length != 0 ||
                objectAttribute is null ||
                objectAttribute.ConstructorArguments.Length != 1 ||
                objectAttribute.ConstructorArguments[0].Value is not ulong objectId ||
                objectId == 0 ||
                !objectIds.Add(objectId))
            {
                diagnostics.Add(Diagnostic.Create(InvalidObject, GetLocation(type), type.Name));
                valid = false;
                continue;
            }

            objects.Add(new ObjectInfo(type, objectId));
        }

        ObjectInfo? rootObject = objects.FirstOrDefault(objectInfo => SymbolEqualityComparer.Default.Equals(objectInfo.Symbol, root));
        if (rootObject is null)
        {
            diagnostics.Add(Diagnostic.Create(InvalidContract, GetLocation(root), root.Name, "the root must also declare a non-zero [LiveObject] ID"));
            return null;
        }

        var memberIds = new HashSet<uint>();
        foreach (ObjectInfo objectInfo in objects)
        {
            foreach (ISymbol member in objectInfo.Symbol.GetMembers())
            {
                if (member is IEventSymbol)
                {
                    diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name, "events are not supported"));
                    valid = false;
                    continue;
                }

                if (member is not IMethodSymbol && member is not IPropertySymbol)
                {
                    continue;
                }

                if (member is IMethodSymbol { MethodKind: MethodKind.PropertyGet or MethodKind.PropertySet })
                {
                    continue;
                }

                AttributeData? memberAttribute = GetAttribute(member, "LiveMemberAttribute");
                if (memberAttribute is null)
                {
                    diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name, "every declared method and property must have [LiveMember]"));
                    valid = false;
                    continue;
                }

                if (memberAttribute.ConstructorArguments.Length != 1 ||
                    memberAttribute.ConstructorArguments[0].Value is not uint memberId ||
                    memberId == 0 ||
                    !memberIds.Add(memberId))
                {
                    diagnostics.Add(Diagnostic.Create(InvalidMember, GetLocation(member), member.Name));
                    valid = false;
                    continue;
                }

                uint setterId = GetNamedUInt(memberAttribute, "SetterId");
                ulong resultObjectId = GetNamedULong(memberAttribute, "ResultObjectId");
                int maximumUtf8Bytes = GetNamedInt(memberAttribute, "MaximumUtf8Bytes");
                int maximumCollectionCount = GetNamedInt(memberAttribute, "MaximumCollectionCount");

                if (member is IPropertySymbol property)
                {
                    if (property.IsIndexer || property.IsStatic || property.GetMethod is null)
                    {
                        diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name, "indexers, static properties, and write-only properties are not supported"));
                        valid = false;
                        continue;
                    }

                    if (property.SetMethod is not null)
                    {
                        if (setterId == 0 || !memberIds.Add(setterId))
                        {
                            diagnostics.Add(Diagnostic.Create(InvalidSetter, GetLocation(member), member.Name));
                            valid = false;
                            continue;
                        }
                    }
                    else if (setterId != 0)
                    {
                        diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name, "a getter-only property cannot declare SetterId"));
                        valid = false;
                        continue;
                    }

                    if (IsString(property.Type))
                    {
                        if (!HasValidUtf8Cap(maximumUtf8Bytes))
                        {
                            diagnostics.Add(Diagnostic.Create(MissingStringCap, GetLocation(member), member.Name));
                            valid = false;
                            continue;
                        }

                        objectInfo.Members.Add(new MemberInfo(objectInfo, member, memberId, setterId, resultObjectId,
                            maximumUtf8Bytes, maximumCollectionCount, MemberShape.StringProperty, null));
                        continue;
                    }

                    if (property.Type.SpecialType == SpecialType.System_Int32 && property.SetMethod is null)
                    {
                        if (maximumCollectionCount <= 0)
                        {
                            diagnostics.Add(Diagnostic.Create(MissingCollectionCap, GetLocation(member), member.Name));
                            valid = false;
                            continue;
                        }

                        objectInfo.Members.Add(new MemberInfo(objectInfo, member, memberId, setterId, resultObjectId,
                            maximumUtf8Bytes, maximumCollectionCount, MemberShape.CountProperty, null));
                        continue;
                    }

                    if (TryGetReadOnlyListElement(property.Type, out INamedTypeSymbol? elementType))
                    {
                        ObjectInfo? resultObject = FindObject(objects, resultObjectId);
                        if (resultObject is null || FindObject(objects, elementType!) is null)
                        {
                            diagnostics.Add(Diagnostic.Create(MissingResultObject, GetLocation(member), member.Name));
                            valid = false;
                            continue;
                        }

                        if (property.SetMethod is not null || maximumCollectionCount <= 0)
                        {
                            diagnostics.Add(Diagnostic.Create(MissingCollectionCap, GetLocation(member), member.Name));
                            valid = false;
                            continue;
                        }

                        objectInfo.Members.Add(new MemberInfo(objectInfo, member, memberId, setterId, resultObjectId,
                            maximumUtf8Bytes, maximumCollectionCount, MemberShape.CollectionProperty, elementType));
                        continue;
                    }

                    diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name,
                        DescribeUnsupportedType(property.Type)));
                    valid = false;
                    continue;
                }

                IMethodSymbol method = (IMethodSymbol)member;
                if (method.IsStatic ||
                    method.MethodKind != MethodKind.Ordinary ||
                    method.TypeParameters.Length != 0 ||
                    method.Parameters.Any(static parameter => parameter.RefKind != RefKind.None || IsBanned(parameter.Type)) ||
                    IsBanned(method.ReturnType))
                {
                    diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name,
                        "generic, static, ref/out, delegate, dynamic, task, credential, and unsupported member forms are not supported"));
                    valid = false;
                    continue;
                }

                ObjectInfo? returnedObject = FindObject(objects, method.ReturnType);
                if (returnedObject is null || resultObjectId == 0 || resultObjectId != returnedObject.Id)
                {
                    diagnostics.Add(Diagnostic.Create(MissingResultObject, GetLocation(member), member.Name));
                    valid = false;
                    continue;
                }

                if (method.Parameters.Length == 1 && IsString(method.Parameters[0].Type))
                {
                    if (!HasValidUtf8Cap(maximumUtf8Bytes))
                    {
                        diagnostics.Add(Diagnostic.Create(MissingStringCap, GetLocation(member), member.Name));
                        valid = false;
                        continue;
                    }

                    objectInfo.Members.Add(new MemberInfo(objectInfo, member, memberId, setterId, resultObjectId,
                        maximumUtf8Bytes, maximumCollectionCount, MemberShape.StringToObjectMethod, method.ReturnType));
                    continue;
                }

                if (method.Parameters.Length == 1 && method.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
                {
                    objectInfo.Members.Add(new MemberInfo(objectInfo, member, memberId, setterId, resultObjectId,
                        maximumUtf8Bytes, maximumCollectionCount, MemberShape.IntToObjectMethod, method.ReturnType));
                    continue;
                }

                diagnostics.Add(Diagnostic.Create(UnsupportedSurface, GetLocation(member), member.Name,
                    "only string-to-live-object and int-to-live-object methods are supported"));
                valid = false;
            }
        }

        if (!valid)
        {
            return null;
        }

        MemberInfo[] rootMethods = rootObject.Members.Where(static member => member.Shape == MemberShape.StringToObjectMethod).ToArray();
        MemberInfo[] rootCollections = rootObject.Members.Where(static member => member.Shape == MemberShape.CollectionProperty).ToArray();
        if (objects.Count != 3 || rootMethods.Length != 1 || rootCollections.Length != 1)
        {
            diagnostics.Add(Diagnostic.Create(RestrictedGraph, GetLocation(root), root.Name));
            return null;
        }

        MemberInfo add = rootMethods[0];
        MemberInfo collection = rootCollections[0];
        ObjectInfo collectionObject = FindObject(objects, collection.ResultObjectId)!;
        ObjectInfo childObject = FindObject(objects, collection.ResultType!)!;
        if (!SymbolEqualityComparer.Default.Equals(add.ResultType, childObject.Symbol))
        {
            diagnostics.Add(Diagnostic.Create(RestrictedGraph, GetLocation(add.Symbol), add.Symbol.Name));
            return null;
        }

        MemberInfo[] countMembers = collectionObject.Members.Where(static member => member.Shape == MemberShape.CountProperty).ToArray();
        MemberInfo[] getAtMembers = collectionObject.Members.Where(static member => member.Shape == MemberShape.IntToObjectMethod).ToArray();
        if (collectionObject.Members.Count != 2 ||
            countMembers.Length != 1 ||
            getAtMembers.Length != 1 ||
            !SymbolEqualityComparer.Default.Equals(getAtMembers[0].ResultType, childObject.Symbol) ||
            countMembers[0].MaximumCollectionCount != collection.MaximumCollectionCount)
        {
            diagnostics.Add(Diagnostic.Create(RestrictedGraph, GetLocation(collectionObject.Symbol), collectionObject.Symbol.Name));
            return null;
        }

        List<MemberInfo> childStrings = childObject.Members.Where(static member => member.Shape == MemberShape.StringProperty).ToList();
        if (childStrings.Count != childObject.Members.Count || childStrings.Count == 0)
        {
            diagnostics.Add(Diagnostic.Create(RestrictedGraph, GetLocation(childObject.Symbol), childObject.Symbol.Name));
            return null;
        }

        IParameterSymbol addParameter = ((IMethodSymbol)add.Symbol).Parameters[0];
        MemberInfo? initialProperty = childStrings.FirstOrDefault(member =>
            string.Equals(member.Symbol.Name, addParameter.Name, StringComparison.OrdinalIgnoreCase) &&
            member.SetterId != 0);
        initialProperty ??= childStrings.FirstOrDefault(static member => member.SetterId != 0);
        if (initialProperty is null)
        {
            diagnostics.Add(Diagnostic.Create(RestrictedGraph, GetLocation(add.Symbol), add.Symbol.Name));
            return null;
        }

        return new ContractInfo(
            root,
            root.ContainingNamespace.IsGlobalNamespace ? string.Empty : root.ContainingNamespace.ToDisplayString(),
            contractId,
            major,
            minor,
            parsedInterfaceId.ToString("D").ToUpperInvariant(),
            rootObject, collectionObject, childObject, add, collection, countMembers[0], getAtMembers[0], childStrings, initialProperty);
    }

    private static void EmitConstants(StringBuilder source, ContractInfo contract, string mode)
    {
        string generated = GeneratedName(contract);
        source.Append("internal static class ").Append(generated).AppendLine();
        source.AppendLine("{");
        source.Append("    internal const string ContractId = \"").Append(EscapeString(contract.ContractId)).AppendLine("\";");
        source.Append("    internal const int MajorVersion = ").Append(contract.MajorVersion.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
        source.Append("    internal const int MinorVersion = ").Append(contract.MinorVersion.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
        source.Append("    internal const string InterfaceId = \"").Append(EscapeString(contract.InterfaceId)).AppendLine("\";");
        source.Append("    internal const uint ContractHash = 0x").Append(ComputeHash(contract).ToString("X8", CultureInfo.InvariantCulture)).AppendLine("U;");
        source.Append("    internal const string Mode = \"").Append(mode).AppendLine("\";");
        foreach (ObjectInfo objectInfo in contract.Objects.OrderBy(static objectInfo => objectInfo.Id))
        {
            source.Append("    internal const ulong Object").Append(objectInfo.Id.ToString(CultureInfo.InvariantCulture)).Append(" = ")
                .Append(objectInfo.Id.ToString(CultureInfo.InvariantCulture)).AppendLine("UL;");
            foreach (MemberInfo member in objectInfo.Members.OrderBy(static member => member.Id))
            {
                source.Append("    internal const uint Member").Append(member.Id.ToString(CultureInfo.InvariantCulture)).Append(" = ")
                    .Append(member.Id.ToString(CultureInfo.InvariantCulture)).AppendLine("U;");
                source.Append("    internal const byte Member").Append(member.Id.ToString(CultureInfo.InvariantCulture)).Append("ResultKind = ")
                    .Append(GetResultKind(member).ToString(CultureInfo.InvariantCulture)).AppendLine(";");
                if (member.ResultObjectId != 0)
                {
                    source.Append("    internal const ulong Member").Append(member.Id.ToString(CultureInfo.InvariantCulture)).Append("ResultObjectId = ")
                        .Append(member.ResultObjectId.ToString(CultureInfo.InvariantCulture)).AppendLine("UL;");
                }
                if (member.MaximumUtf8Bytes != 0)
                {
                    source.Append("    internal const int Member").Append(member.Id.ToString(CultureInfo.InvariantCulture)).Append("MaximumUtf8Bytes = ")
                        .Append(member.MaximumUtf8Bytes.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
                }
                if (member.MaximumCollectionCount != 0)
                {
                    source.Append("    internal const int Member").Append(member.Id.ToString(CultureInfo.InvariantCulture)).Append("MaximumCollectionCount = ")
                        .Append(member.MaximumCollectionCount.ToString(CultureInfo.InvariantCulture)).AppendLine(";");
                }
                if (member.SetterId != 0)
                {
                    source.Append("    internal const uint Member").Append(member.SetterId.ToString(CultureInfo.InvariantCulture)).Append(" = ")
                        .Append(member.SetterId.ToString(CultureInfo.InvariantCulture)).AppendLine("U;");
                }
            }
        }

        source.AppendLine("}");
        source.AppendLine();
    }

    private static void EmitHost(StringBuilder source, ContractInfo contract)
    {
        string prefix = TypePrefix(contract);
        string generated = GeneratedName(contract);
        string model = prefix + "HostModel";
        string childModel = TypePrefix(contract.Child.Symbol) + "HostModel";
        string adapter = prefix + "HostAdapter";
        string initialProperty = EscapeIdentifier(contract.InitialProperty.Symbol.Name);

        source.Append("internal sealed class ").Append(childModel).AppendLine();
        source.AppendLine("{");
        source.Append("    internal ").Append(childModel).AppendLine("(ulong handle) => Handle = handle;");
        source.AppendLine("    internal ulong Handle { get; }");
        foreach (MemberInfo property in contract.ChildStrings)
        {
            source.Append("    internal string ").Append(EscapeIdentifier(property.Symbol.Name)).AppendLine(" { get; set; } = string.Empty;");
        }

        source.AppendLine("}");
        source.AppendLine();
        source.Append("internal sealed class ").Append(model).AppendLine();
        source.AppendLine("{");
        source.Append("    private readonly global::System.Collections.Generic.List<").Append(childModel).AppendLine("> children = [];");
        source.Append("    private readonly global::System.Collections.Generic.Dictionary<ulong, ").Append(childModel).AppendLine("> childrenByHandle = [];");
        source.AppendLine("    internal int Count => children.Count;");
        source.Append("    internal ").Append(childModel).AppendLine(" Add(string value)");
        source.AppendLine("    {");
        source.AppendLine("        ulong handle = AllocateHandle();");
        source.Append("        var child = new ").Append(childModel).Append("(handle) { ").Append(initialProperty).AppendLine(" = value };");
        source.AppendLine("        children.Add(child);");
        source.AppendLine("        childrenByHandle.Add(handle, child);");
        source.AppendLine("        return child;");
        source.AppendLine("    }");
        source.Append("    internal bool TryGetAt(int index, out ").Append(childModel).AppendLine(" child)");
        source.AppendLine("    {");
        source.AppendLine("        if ((uint)index < (uint)children.Count)");
        source.AppendLine("        {");
        source.AppendLine("            child = children[index];");
        source.AppendLine("            return true;");
        source.AppendLine("        }");
        source.AppendLine("        child = null!;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.Append("    internal bool TryGetChild(ulong handle, out ").Append(childModel).AppendLine(" child) => childrenByHandle.TryGetValue(handle, out child!);");
        source.AppendLine("    private ulong AllocateHandle()");
        source.AppendLine("    {");
        source.AppendLine("        ulong handle;");
        source.AppendLine("        do");
        source.AppendLine("        {");
        source.AppendLine("            global::System.Span<byte> bytes = stackalloc byte[sizeof(ulong)];");
        source.AppendLine("            global::System.Security.Cryptography.RandomNumberGenerator.Fill(bytes);");
        source.AppendLine("            handle = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(bytes);");
        source.Append("        } while (handle == 0 || handle == ").Append(generated).Append(".Object").Append(contract.RootObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(" || handle == ").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture)).AppendLine(" || childrenByHandle.ContainsKey(handle));");
        source.AppendLine("        return handle;");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.Append("internal static class ").Append(adapter).AppendLine();
        source.AppendLine("{");
        source.AppendLine("    internal const int EInvalidArg = unchecked((int)0x80070057);");
        source.AppendLine("    internal const int EBounds = unchecked((int)0x8000000B);");
        source.AppendLine("    internal const int EBufferTooSmall = unchecked((int)0x8007007A);");
        source.AppendLine("    private static readonly global::System.Text.UTF8Encoding StrictUtf8 = new(false, true);");
        source.Append("    internal static int TryInvoke(").Append(model).AppendLine(" model, ulong objectId, uint memberId, byte inputTag, global::System.ReadOnlySpan<byte> input, int outputCapacity, out byte[] output, out int outputLength)");
        source.AppendLine("    {");
        source.AppendLine("        output = global::System.Array.Empty<byte>();");
        source.AppendLine("        outputLength = 0;");
        source.AppendLine("        if (outputCapacity < 0) return EInvalidArg;");

        EmitHostRootDispatch(source, contract, generated, model, childModel);
        EmitHostCollectionDispatch(source, contract, generated, model, childModel);
        EmitHostChildDispatch(source, contract, generated, childModel);

        source.AppendLine("        return EInvalidArg;");
        source.AppendLine("    }");
        source.AppendLine("    private static bool IsNull(byte tag, global::System.ReadOnlySpan<byte> input) => tag == global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Null && input.IsEmpty;");
        source.AppendLine("    private static bool TryReadString(byte tag, global::System.ReadOnlySpan<byte> input, int maximumBytes, out string value)");
        source.AppendLine("    {");
        source.AppendLine("        value = string.Empty;");
        source.AppendLine("        if (tag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Utf8String || input.IsEmpty || input.Length > maximumBytes) return false;");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            value = StrictUtf8.GetString(input);");
        source.AppendLine("            return value.IndexOf('\\0') < 0;");
        source.AppendLine("        }");
        source.AppendLine("        catch (global::System.ArgumentException)");
        source.AppendLine("        {");
        source.AppendLine("            return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("    private static int ReserveOutput(int length, int outputCapacity, out byte[] output, out int outputLength)");
        source.AppendLine("    {");
        source.AppendLine("        output = global::System.Array.Empty<byte>();");
        source.AppendLine("        outputLength = length;");
        source.AppendLine("        return outputCapacity < length ? EBufferTooSmall : 0;");
        source.AppendLine("    }");
        source.AppendLine("    private static int WriteOutput(byte[] value, int outputCapacity, out byte[] output, out int outputLength)");
        source.AppendLine("    {");
        source.AppendLine("        outputLength = value.Length;");
        source.AppendLine("        if (outputCapacity < value.Length)");
        source.AppendLine("        {");
        source.AppendLine("            output = global::System.Array.Empty<byte>();");
        source.AppendLine("            return EBufferTooSmall;");
        source.AppendLine("        }");
        source.AppendLine("        output = value;");
        source.AppendLine("        return 0;");
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static void EmitHostRootDispatch(StringBuilder source, ContractInfo contract, string generated, string model, string childModel)
    {
        string addMember = "Member" + contract.Add.Id.ToString(CultureInfo.InvariantCulture);
        string collectionMember = "Member" + contract.Collection.Id.ToString(CultureInfo.InvariantCulture);
        source.Append("        if (objectId == ").Append(generated).Append(".Object").Append(contract.RootObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(" && memberId == ").Append(generated).Append('.').Append(addMember).AppendLine(")");
        source.AppendLine("        {");
        source.Append("            if (!TryReadString(inputTag, input, ").Append(contract.Add.MaximumUtf8Bytes.ToString(CultureInfo.InvariantCulture)).AppendLine(", out string value)) return EInvalidArg;");
        source.Append("            if (model.Count >= ").Append(contract.Collection.MaximumCollectionCount.ToString(CultureInfo.InvariantCulture)).AppendLine(") return EBounds;");
        source.AppendLine("            int status = ReserveOutput(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + sizeof(ulong), outputCapacity, out output, out outputLength);");
        source.AppendLine("            if (status != 0) return status;");
        source.AppendLine("            output = global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.EncodeObjectHandle(model.Add(value).Handle);");
        source.AppendLine("            return 0;");
        source.AppendLine("        }");
        source.Append("        if (objectId == ").Append(generated).Append(".Object").Append(contract.RootObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(" && memberId == ").Append(generated).Append('.').Append(collectionMember).AppendLine(")");
        source.AppendLine("        {");
        source.AppendLine("            if (!IsNull(inputTag, input)) return EInvalidArg;");
        source.Append("            return WriteOutput(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.EncodeObjectHandle(")
            .Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture))
            .AppendLine("), outputCapacity, out output, out outputLength);");
        source.AppendLine("        }");
    }

    private static void EmitHostCollectionDispatch(StringBuilder source, ContractInfo contract, string generated, string model, string childModel)
    {
        string countMember = "Member" + contract.Count.Id.ToString(CultureInfo.InvariantCulture);
        string getAtMember = "Member" + contract.GetAt.Id.ToString(CultureInfo.InvariantCulture);
        source.Append("        if (objectId == ").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(" && memberId == ").Append(generated).Append('.').Append(countMember).AppendLine(")");
        source.AppendLine("        {");
        source.AppendLine("            if (!IsNull(inputTag, input) || model.Count > " + contract.Collection.MaximumCollectionCount.ToString(CultureInfo.InvariantCulture) + ") return EInvalidArg;");
        source.AppendLine("            return WriteOutput(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.EncodeInt32(model.Count), outputCapacity, out output, out outputLength);");
        source.AppendLine("        }");
        source.Append("        if (objectId == ").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(" && memberId == ").Append(generated).Append('.').Append(getAtMember).AppendLine(")");
        source.AppendLine("        {");
        source.AppendLine("            if (inputTag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Int32 || input.Length != sizeof(int)) return EInvalidArg;");
        source.AppendLine("            int index = global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(input);");
        source.Append("            if ((uint)index >= (uint)model.Count || index >= ").Append(contract.Collection.MaximumCollectionCount.ToString(CultureInfo.InvariantCulture)).AppendLine(") return EBounds;");
        source.AppendLine("            if (!model.TryGetAt(index, out var indexedChild)) return EBounds;");
        source.AppendLine("            return WriteOutput(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.EncodeObjectHandle(indexedChild.Handle), outputCapacity, out output, out outputLength);");
        source.AppendLine("        }");
    }

    private static void EmitHostChildDispatch(StringBuilder source, ContractInfo contract, string generated, string childModel)
    {
        source.AppendLine("        if (!model.TryGetChild(objectId, out var child)) return EInvalidArg;");
        foreach (MemberInfo property in contract.ChildStrings)
        {
            string member = "Member" + property.Id.ToString(CultureInfo.InvariantCulture);
            string propertyName = EscapeIdentifier(property.Symbol.Name);
            source.Append("        if (memberId == ").Append(generated).Append('.').Append(member).AppendLine(")");
            source.AppendLine("        {");
            source.AppendLine("            if (!IsNull(inputTag, input)) return EInvalidArg;");
            source.Append("            return WriteOutput(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.EncodeString(child.").Append(propertyName)
                .AppendLine("), outputCapacity, out output, out outputLength);");
            source.AppendLine("        }");
            if (property.SetterId != 0)
            {
                string setter = "Member" + property.SetterId.ToString(CultureInfo.InvariantCulture);
                source.Append("        if (memberId == ").Append(generated).Append('.').Append(setter).AppendLine(")");
                source.AppendLine("        {");
                source.Append("            if (!TryReadString(inputTag, input, ").Append(property.MaximumUtf8Bytes.ToString(CultureInfo.InvariantCulture)).AppendLine(", out string value)) return EInvalidArg;");
                source.AppendLine("            byte[] result = global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Encode(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Null, global::System.Array.Empty<byte>());");
                source.AppendLine("            int status = WriteOutput(result, outputCapacity, out output, out outputLength);");
                source.AppendLine("            if (status != 0) return status;");
                source.Append("            child.").Append(propertyName).AppendLine(" = value;");
                source.AppendLine("            return 0;");
                source.AppendLine("        }");
            }
        }
    }

    private static void EmitPayload(StringBuilder source, ContractInfo contract)
    {
        string prefix = TypePrefix(contract);
        string generated = GeneratedName(contract);
        string rootProxy = prefix + "Proxy";
        string childProxy = TypePrefix(contract.Child.Symbol) + "Proxy";
        string collectionProxy = TypePrefix(contract.CollectionObject.Symbol) + "Proxy";
        string client = prefix + "PayloadClient";
        string broker = "global::Devolutions.PowerShell.Ffi.LiveObjects.IPowerShellLiveObjectBrokerContract";
        string comObject = "global::System.Runtime.InteropServices.Marshalling.ComObject";

        source.Append("public sealed class ").Append(rootProxy).AppendLine(" : global::System.IDisposable");
        source.AppendLine("{");
        source.Append("    private readonly ").Append(client).AppendLine(" client;");
        source.Append("    private readonly global::System.Collections.Generic.Dictionary<ulong, ").Append(childProxy).AppendLine("> children = [];");
        source.Append("    private ").Append(collectionProxy).AppendLine("? collection;");
        source.Append("    private ").Append(rootProxy).Append('(').Append(client).AppendLine(" client) => this.client = client;");
        source.Append("    internal static ").Append(rootProxy).Append(" Create(").Append(broker).Append(" value, ").Append(comObject).AppendLine(" comObject)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(value);");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(comObject);");
        source.Append("        return new ").Append(rootProxy).AppendLine("(new " + client + "(value, comObject));");
        source.AppendLine("    }");
        source.Append("    public ").Append(childProxy).Append(' ').Append(EscapeIdentifier(contract.Add.Symbol.Name)).AppendLine("(string value)");
        source.AppendLine("    {");
        source.Append("        return GetOrAddChild(client.InvokeHandle(").Append(generated).Append(".Object").Append(contract.RootObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(", ").Append(generated).Append(".Member").Append(contract.Add.Id.ToString(CultureInfo.InvariantCulture)).Append(", ")
            .Append("client.EncodeString(value, ").Append(contract.Add.MaximumUtf8Bytes.ToString(CultureInfo.InvariantCulture)).AppendLine(")));");
        source.AppendLine("    }");
        source.Append("    public ").Append(collectionProxy).Append(' ').Append(EscapeIdentifier(contract.Collection.Symbol.Name)).AppendLine();
        source.AppendLine("    {");
        source.AppendLine("        get");
        source.AppendLine("        {");
        source.AppendLine("            if (collection is not null) return collection;");
        source.Append("            ulong handle = client.InvokeHandle(").Append(generated).Append(".Object").Append(contract.RootObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(", ").Append(generated).Append(".Member").Append(contract.Collection.Id.ToString(CultureInfo.InvariantCulture)).Append(", ")
            .AppendLine("client.EncodeNull());");
        source.Append("            if (handle != ").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture)).AppendLine(") throw new global::System.InvalidOperationException(\"Broker returned an invalid collection handle.\");");
        source.Append("            return collection = new ").Append(collectionProxy).AppendLine("(this);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.Append("    internal ").Append(childProxy).AppendLine(" GetOrAddChild(ulong handle)");
        source.AppendLine("    {");
        source.Append("        if (handle == 0 || handle == ").Append(generated).Append(".Object").Append(contract.RootObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(" || handle == ").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture)).AppendLine(") throw new global::System.InvalidOperationException(\"Broker returned an invalid child handle.\");");
        source.AppendLine("        if (!children.TryGetValue(handle, out var child))");
        source.AppendLine("        {");
        source.Append("            child = new ").Append(childProxy).AppendLine("(client, handle);");
        source.AppendLine("            children.Add(handle, child);");
        source.AppendLine("        }");
        source.AppendLine("        return child;");
        source.AppendLine("    }");
        source.AppendLine("    internal int GetChildCount()");
        source.AppendLine("    {");
        source.Append("        int count = client.InvokeInt32(").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(", ").Append(generated).Append(".Member").Append(contract.Count.Id.ToString(CultureInfo.InvariantCulture)).AppendLine(", client.EncodeNull());");
        source.Append("        if (count < 0 || count > ").Append(contract.Collection.MaximumCollectionCount.ToString(CultureInfo.InvariantCulture)).AppendLine(") throw new global::System.InvalidOperationException(\"Broker returned an invalid collection count.\");");
        source.AppendLine("        return count;");
        source.AppendLine("    }");
        source.Append("    internal ").Append(childProxy).AppendLine(" GetChildAt(int index)");
        source.AppendLine("    {");
        source.Append("        return GetOrAddChild(client.InvokeHandle(").Append(generated).Append(".Object").Append(contract.CollectionObject.Id.ToString(CultureInfo.InvariantCulture))
            .Append(", ").Append(generated).Append(".Member").Append(contract.GetAt.Id.ToString(CultureInfo.InvariantCulture)).AppendLine(", client.EncodeInt32(index)));");
        source.AppendLine("    }");
        source.AppendLine("    public void Dispose() => client.Dispose();");
        source.AppendLine("}");
        source.AppendLine();

        source.Append("public sealed class ").Append(childProxy).AppendLine();
        source.AppendLine("{");
        source.Append("    private readonly ").Append(client).AppendLine(" client;");
        source.AppendLine("    private readonly ulong handle;");
        source.Append("    internal ").Append(childProxy).Append('(').Append(client).AppendLine(" client, ulong handle) { this.client = client; this.handle = handle; }");
        foreach (MemberInfo property in contract.ChildStrings)
        {
            string propertyName = EscapeIdentifier(property.Symbol.Name);
            source.Append("    public string ").Append(propertyName).AppendLine();
            source.AppendLine("    {");
            source.Append("        get => client.InvokeString(handle, ").Append(generated).Append(".Member").Append(property.Id.ToString(CultureInfo.InvariantCulture))
                .Append(", client.EncodeNull(), ").Append(property.MaximumUtf8Bytes.ToString(CultureInfo.InvariantCulture)).AppendLine(");");
            if (property.SetterId != 0)
            {
                source.Append("        set => client.InvokeVoid(handle, ").Append(generated).Append(".Member").Append(property.SetterId.ToString(CultureInfo.InvariantCulture))
                    .Append(", client.EncodeString(value, ").Append(property.MaximumUtf8Bytes.ToString(CultureInfo.InvariantCulture)).AppendLine("));");
            }
            source.AppendLine("    }");
            source.Append("    public string Read").Append(EscapeIdentifier(property.Symbol.Name)).Append("() => ").Append(propertyName).AppendLine(";");
        }
        source.AppendLine("}");
        source.AppendLine();

        source.Append("public sealed class ").Append(collectionProxy).Append(" : global::System.Collections.Generic.IReadOnlyList<").Append(childProxy).AppendLine(">");
        source.AppendLine("{");
        source.Append("    private readonly ").Append(rootProxy).AppendLine(" root;");
        source.Append("    internal ").Append(collectionProxy).Append('(').Append(rootProxy).AppendLine(" root) => this.root = root;");
        source.AppendLine("    public int Count => root.GetChildCount();");
        source.Append("    public ").Append(childProxy).AppendLine(" this[int index]");
        source.AppendLine("    {");
        source.AppendLine("        get");
        source.AppendLine("        {");
        source.AppendLine("            int count = Count;");
        source.AppendLine("            if ((uint)index >= (uint)count) throw new global::System.ArgumentOutOfRangeException(nameof(index));");
        source.AppendLine("            return root.GetChildAt(index);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.Append("    public global::System.Collections.Generic.IEnumerator<").Append(childProxy).AppendLine("> GetEnumerator()");
        source.AppendLine("    {");
        source.AppendLine("        int count = Count;");
        source.AppendLine("        for (int index = 0; index < count; index++) yield return this[index];");
        source.AppendLine("    }");
        source.AppendLine("    global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();");
        source.AppendLine("}");
        source.AppendLine();
        EmitPayloadClient(source, contract, generated, client, broker, comObject, rootProxy);
    }

    private static void EmitPayloadClient(StringBuilder source, ContractInfo contract, string generated, string client, string broker, string comObject, string rootProxy)
    {
        source.Append("internal sealed class ").Append(client).AppendLine(" : global::System.IDisposable");
        source.AppendLine("{");
        source.AppendLine("    private const int EAccessDenied = unchecked((int)0x80070005);");
        source.AppendLine("    private const int EBufferTooSmall = unchecked((int)0x8007007A);");
        source.AppendLine("    private static readonly global::System.Text.UTF8Encoding StrictUtf8 = new(false, true);");
        source.AppendLine("    private readonly object gate = new();");
        source.Append("    private ").Append(broker).AppendLine("? value;");
        source.Append("    private ").Append(comObject).AppendLine("? comObject;");
        source.AppendLine("    private readonly ulong leaseId;");
        source.AppendLine("    private readonly uint generation;");
        source.Append("    internal ").Append(client).Append('(').Append(broker).Append(" value, ").Append(comObject).AppendLine(" comObject)");
        source.AppendLine("    {");
        source.AppendLine("        this.value = value;");
        source.AppendLine("        this.comObject = comObject;");
        source.AppendLine("        (leaseId, generation) = OpenLease(value);");
        source.AppendLine("    }");
        source.Append("    ~").Append(client).AppendLine("()");
        source.AppendLine("    {");
        source.AppendLine("        try { ReleaseComObject(); } catch { }");
        source.AppendLine("    }");
        source.AppendLine("    internal byte[] EncodeNull() => global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Encode(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Null, global::System.Array.Empty<byte>());");
        source.AppendLine("    internal byte[] EncodeInt32(int value) => global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.EncodeInt32(value);");
        source.AppendLine("    internal byte[] EncodeString(string value, int maximumBytes)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(value);");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            if (value.IndexOf('\\0') >= 0 || StrictUtf8.GetByteCount(value) > maximumBytes) throw new global::System.ArgumentOutOfRangeException(nameof(value));");
        source.AppendLine("            return global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Encode(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Utf8String, StrictUtf8.GetBytes(value));");
        source.AppendLine("        }");
        source.AppendLine("        catch (global::System.ArgumentException exception) when (exception is not global::System.ArgumentOutOfRangeException)");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.ArgumentException(\"The value is not valid UTF-8 text.\", nameof(value), exception);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("    internal ulong InvokeHandle(ulong objectId, uint memberId, byte[] input)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] output = Invoke(objectId, memberId, input);");
        source.AppendLine("        if (!global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.TryDecode(output, out byte tag, out global::System.ReadOnlySpan<byte> payload) || tag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.ObjectHandle || payload.Length != sizeof(ulong)) throw new global::System.InvalidOperationException(\"Broker returned an invalid object handle.\");");
        source.AppendLine("        ulong handle = global::System.Buffers.Binary.BinaryPrimitives.ReadUInt64LittleEndian(payload);");
        source.AppendLine("        return handle == 0 ? throw new global::System.InvalidOperationException(\"Broker returned an invalid object handle.\") : handle;");
        source.AppendLine("    }");
        source.AppendLine("    internal int InvokeInt32(ulong objectId, uint memberId, byte[] input)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] output = Invoke(objectId, memberId, input);");
        source.AppendLine("        if (!global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.TryDecode(output, out byte tag, out global::System.ReadOnlySpan<byte> payload) || tag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Int32 || payload.Length != sizeof(int)) throw new global::System.InvalidOperationException(\"Broker returned an invalid integer.\");");
        source.AppendLine("        return global::System.Buffers.Binary.BinaryPrimitives.ReadInt32LittleEndian(payload);");
        source.AppendLine("    }");
        source.AppendLine("    internal string InvokeString(ulong objectId, uint memberId, byte[] input, int maximumBytes)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] output = Invoke(objectId, memberId, input);");
        source.AppendLine("        if (!global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.TryDecode(output, out byte tag, out global::System.ReadOnlySpan<byte> payload) || tag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Utf8String || payload.Length > maximumBytes || !TryDecodeString(payload, out string value)) throw new global::System.InvalidOperationException(\"Broker returned an invalid string.\");");
        source.AppendLine("        return value;");
        source.AppendLine("    }");
        source.AppendLine("    internal void InvokeVoid(ulong objectId, uint memberId, byte[] input)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] output = Invoke(objectId, memberId, input);");
        source.AppendLine("        if (!global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.TryDecode(output, out byte tag, out global::System.ReadOnlySpan<byte> payload) || tag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Null || !payload.IsEmpty) throw new global::System.InvalidOperationException(\"Broker returned an invalid void result.\");");
        source.AppendLine("    }");
        source.AppendLine("    private byte[] Invoke(ulong objectId, uint memberId, byte[] input)");
        source.AppendLine("    {");
        source.AppendLine("        lock (gate)");
        source.AppendLine("        {");
        source.Append("            ").Append(broker).Append(" broker = value ?? throw new global::System.ObjectDisposedException(nameof(").Append(rootProxy).AppendLine("));");
        source.AppendLine("            global::System.IntPtr inputBuffer = global::System.IntPtr.Zero;");
        source.AppendLine("            global::System.IntPtr outputBuffer = global::System.IntPtr.Zero;");
        source.AppendLine("            try");
        source.AppendLine("            {");
        source.AppendLine("                inputBuffer = global::System.Runtime.InteropServices.Marshal.AllocHGlobal(input.Length);");
        source.AppendLine("                outputBuffer = global::System.Runtime.InteropServices.Marshal.AllocHGlobal(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.MaximumValueBytes);");
        source.AppendLine("                global::System.Runtime.InteropServices.Marshal.Copy(input, 0, inputBuffer, input.Length);");
        source.AppendLine("                int status = broker.Invoke(leaseId, generation, objectId, memberId, inputBuffer, input.Length, outputBuffer, global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.MaximumValueBytes, out int outputLength);");
        source.AppendLine("                if (status == EAccessDenied) throw new global::System.ObjectDisposedException(nameof(" + rootProxy + "), \"The host invocation lease has ended.\");");
        source.AppendLine("                if (status == EBufferTooSmall || outputLength < global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize || outputLength > global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.MaximumValueBytes) throw new global::System.InvalidOperationException(\"Broker output exceeds the bounded payload buffer.\");");
        source.AppendLine("                if (status != 0) throw new global::System.Runtime.InteropServices.COMException(\"Broker invocation failed.\", status);");
        source.AppendLine("                byte[] output = new byte[outputLength];");
        source.AppendLine("                global::System.Runtime.InteropServices.Marshal.Copy(outputBuffer, output, 0, outputLength);");
        source.AppendLine("                return output;");
        source.AppendLine("            }");
        source.AppendLine("            finally");
        source.AppendLine("            {");
        source.AppendLine("                if (inputBuffer != global::System.IntPtr.Zero) global::System.Runtime.InteropServices.Marshal.FreeHGlobal(inputBuffer);");
        source.AppendLine("                if (outputBuffer != global::System.IntPtr.Zero) global::System.Runtime.InteropServices.Marshal.FreeHGlobal(outputBuffer);");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("    // The host owns EndLease; retained child wrappers must observe its tombstone.");
        source.AppendLine("    public void Dispose() { }");
        source.AppendLine("    private void ReleaseComObject()");
        source.AppendLine("    {");
        source.AppendLine("        lock (gate)");
        source.AppendLine("        {");
        source.AppendLine("            var release = comObject;");
        source.AppendLine("            comObject = null;");
        source.AppendLine("            value = null;");
        source.AppendLine("            release?.FinalRelease();");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.Append("    private static (ulong LeaseId, uint Generation) OpenLease(").Append(broker).AppendLine(" broker)");
        source.AppendLine("    {");
        source.AppendLine("        byte[] input = global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Encode(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Null, global::System.Array.Empty<byte>());");
        source.AppendLine("        global::System.IntPtr inputBuffer = global::System.IntPtr.Zero;");
        source.AppendLine("        global::System.IntPtr outputBuffer = global::System.IntPtr.Zero;");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            inputBuffer = global::System.Runtime.InteropServices.Marshal.AllocHGlobal(input.Length);");
        source.AppendLine("            outputBuffer = global::System.Runtime.InteropServices.Marshal.AllocHGlobal(global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.MaximumValueBytes);");
        source.AppendLine("            global::System.Runtime.InteropServices.Marshal.Copy(input, 0, inputBuffer, input.Length);");
        source.AppendLine("            int status = broker.Invoke(0, 0, 0, 0, inputBuffer, input.Length, outputBuffer, global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.MaximumValueBytes, out int outputLength);");
        source.AppendLine("            if (status != 0 || outputLength < global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize || outputLength > global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.HeaderSize + global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.MaximumValueBytes) throw new global::System.Runtime.InteropServices.COMException(\"Broker lease initialization failed.\", status);");
        source.AppendLine("            byte[] output = new byte[outputLength];");
        source.AppendLine("            global::System.Runtime.InteropServices.Marshal.Copy(outputBuffer, output, 0, outputLength);");
        source.AppendLine("            if (!global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.TryDecode(output, out byte tag, out global::System.ReadOnlySpan<byte> payload) || tag != global::Devolutions.PowerShell.Ffi.LiveObjects.PowerShellLiveObjectBrokerWire.Utf8String || !TryDecodeString(payload, out string lease)) throw new global::System.InvalidOperationException(\"Broker returned an invalid lease.\");");
        source.AppendLine("            string[] parts = lease.Split(':');");
        source.Append("            if (parts.Length != 3 || !ulong.TryParse(parts[0], out ulong leaseId) || leaseId == 0 || !uint.TryParse(parts[1], out uint generation) || generation == 0 || !uint.TryParse(parts[2], out uint hash) || hash != ").Append(generated).AppendLine(".ContractHash) throw new global::System.InvalidOperationException(\"Broker returned an invalid lease.\");");
        source.AppendLine("            return (leaseId, generation);");
        source.AppendLine("        }");
        source.AppendLine("        finally");
        source.AppendLine("        {");
        source.AppendLine("            if (inputBuffer != global::System.IntPtr.Zero) global::System.Runtime.InteropServices.Marshal.FreeHGlobal(inputBuffer);");
        source.AppendLine("            if (outputBuffer != global::System.IntPtr.Zero) global::System.Runtime.InteropServices.Marshal.FreeHGlobal(outputBuffer);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("    private static bool TryDecodeString(global::System.ReadOnlySpan<byte> payload, out string value)");
        source.AppendLine("    {");
        source.AppendLine("        value = string.Empty;");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            value = StrictUtf8.GetString(payload);");
        source.AppendLine("            return value.IndexOf('\\0') < 0;");
        source.AppendLine("        }");
        source.AppendLine("        catch (global::System.ArgumentException)");
        source.AppendLine("        {");
        source.AppendLine("            return false;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static string ComputeHashInput(ContractInfo contract)
    {
        StringBuilder canonical = new();
        canonical.Append("contract|").Append(contract.ContractId).Append('|').Append(contract.MajorVersion).Append('|')
            .Append(contract.MinorVersion).Append('|').Append(contract.InterfaceId).Append(';');
        foreach (ObjectInfo objectInfo in contract.Objects.OrderBy(static objectInfo => objectInfo.Id))
        {
            canonical.Append("object|").Append(objectInfo.Id).Append(';');
            foreach (MemberInfo member in objectInfo.Members.OrderBy(static member => member.Id))
            {
                canonical.Append("member|").Append(objectInfo.Id).Append('|').Append(member.Id).Append('|')
                    .Append((int)member.Shape).Append('|').Append(GetTypeShape(member)).Append('|').Append(member.SetterId)
                    .Append('|').Append(member.ResultObjectId).Append('|').Append(member.MaximumUtf8Bytes)
                    .Append('|').Append(member.MaximumCollectionCount).Append(';');
            }
        }

        return canonical.ToString();
    }

    private static uint ComputeHash(ContractInfo contract)
    {
        uint hash = 2166136261;
        foreach (byte value in Encoding.UTF8.GetBytes(ComputeHashInput(contract)))
        {
            hash ^= value;
            hash *= 16777619;
        }

        return hash;
    }

    private static string GetTypeShape(MemberInfo member)
    {
        return member.Shape switch
        {
            MemberShape.StringProperty => member.SetterId == 0 ? "()->string" : "()->string;(string)->void",
            MemberShape.CollectionProperty => $"()->IReadOnlyList<{member.ResultType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>",
            MemberShape.CountProperty => "()->int",
            MemberShape.StringToObjectMethod => $"(string)->{member.ResultType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}",
            MemberShape.IntToObjectMethod => $"(int)->{member.ResultType!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}",
            _ => throw new InvalidOperationException(),
        };
    }

    private static byte GetResultKind(MemberInfo member)
    {
        return member.Shape switch
        {
            MemberShape.StringProperty => 1,
            MemberShape.CollectionProperty => 2,
            MemberShape.StringToObjectMethod or MemberShape.IntToObjectMethod => 3,
            MemberShape.CountProperty => 4,
            _ => 0,
        };
    }

    private static bool IsString(ITypeSymbol type) => type.SpecialType == SpecialType.System_String;

    private static bool TryGetReadOnlyListElement(ITypeSymbol type, out INamedTypeSymbol? element)
    {
        element = null;
        if (type is not INamedTypeSymbol named ||
            named.Name != "IReadOnlyList" ||
            named.ContainingNamespace.ToDisplayString() != "System.Collections.Generic" ||
            named.TypeArguments.Length != 1 ||
            named.TypeArguments[0] is not INamedTypeSymbol candidate)
        {
            return false;
        }

        element = candidate;
        return true;
    }

    private static bool IsBanned(ITypeSymbol type)
    {
        if (type.TypeKind is TypeKind.Dynamic or TypeKind.Delegate ||
            type.SpecialType == SpecialType.System_Object)
        {
            return true;
        }

        string name = type.Name;
        return name.IndexOf("Task", StringComparison.OrdinalIgnoreCase) >= 0 ||
            name.IndexOf("SecureString", StringComparison.OrdinalIgnoreCase) >= 0 ||
            name.IndexOf("PSCredential", StringComparison.OrdinalIgnoreCase) >= 0 ||
            name.IndexOf("Credential", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    private static string DescribeUnsupportedType(ITypeSymbol type) =>
        IsBanned(type) ? "dynamic, delegate, task, credential, and object-like types are not supported" :
        $"the type '{type.ToDisplayString()}' is not a supported live-member shape";

    private static bool HasValidUtf8Cap(int value) => value > 0 && value <= MaximumWireBytes;

    private static ObjectInfo? FindObject(IEnumerable<ObjectInfo> objects, ulong id) =>
        objects.FirstOrDefault(objectInfo => objectInfo.Id == id);

    private static ObjectInfo? FindObject(IEnumerable<ObjectInfo> objects, ITypeSymbol type) =>
        objects.FirstOrDefault(objectInfo => SymbolEqualityComparer.Default.Equals(objectInfo.Symbol, type));

    private static string GeneratedName(ContractInfo contract) => EscapeIdentifier(contract.Root.Name) + "Generated";
    private static string TypePrefix(ContractInfo contract) => TypePrefix(contract.Root);
    private static string TypePrefix(INamedTypeSymbol type) =>
        EscapeIdentifier(type.Name.Length > 1 && type.Name[0] == 'I' && char.IsUpper(type.Name[1]) ? type.Name.Substring(1) : type.Name);

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static Location GetLocation(ISymbol symbol) => symbol.Locations.FirstOrDefault() ?? Location.None;

    private static bool HasAttribute(ISymbol symbol, string name) => GetAttribute(symbol, name) is not null;

    private static AttributeData? GetAttribute(ISymbol symbol, string name) =>
        symbol.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.Name == name);

    private static uint GetNamedUInt(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value.Value is uint value ? value : 0;

    private static ulong GetNamedULong(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value.Value is ulong value ? value : 0;

    private static int GetNamedInt(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value.Value is int value ? value : 0;

    private static readonly DiagnosticDescriptor MissingMode = new(
        "MPWLC001", "Live contract mode is required",
        "Set LiveContractMode to Host or Payload when compiling a [LiveContract] declaration",
        "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor InvalidContract = new(
        "MPWLC002", "Invalid live contract",
        "Live contract '{0}' is invalid: {1}", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor InvalidObject = new(
        "MPWLC003", "Invalid live object",
        "Live object '{0}' must declare a globally unique, non-zero object ID", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor InvalidMember = new(
        "MPWLC004", "Invalid live member",
        "Live member '{0}' must declare a globally unique, non-zero member ID", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor InvalidSetter = new(
        "MPWLC005", "Invalid live setter",
        "Mutable live property '{0}' must declare a globally unique, non-zero SetterId", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor MissingStringCap = new(
        "MPWLC006", "String member requires a bound",
        "Live string member '{0}' must declare MaximumUtf8Bytes between 1 and 256", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor MissingCollectionCap = new(
        "MPWLC007", "Collection member requires a bound",
        "Live collection member '{0}' must declare a positive MaximumCollectionCount", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor MissingResultObject = new(
        "MPWLC008", "Live object result is unresolved",
        "Live member '{0}' must declare ResultObjectId for a matching live-object result kind", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor UnsupportedSurface = new(
        "MPWLC009", "Unsupported live contract surface",
        "Live member or object '{0}' is unsupported: {1}", "LiveContract", DiagnosticSeverity.Error, true);

    private static readonly DiagnosticDescriptor RestrictedGraph = new(
        "MPWLC010", "Unsupported live contract graph",
        "Live contract '{0}' must contain exactly a root string-to-child method, a bounded child collection, Count, GetAt, and string child properties", "LiveContract", DiagnosticSeverity.Error, true);

    private sealed class ObjectInfo
    {
        internal ObjectInfo(INamedTypeSymbol symbol, ulong id)
        {
            Symbol = symbol;
            Id = id;
        }

        internal INamedTypeSymbol Symbol { get; }
        internal ulong Id { get; }
        internal List<MemberInfo> Members { get; } = new();
    }

    private sealed class MemberInfo
    {
        internal MemberInfo(ObjectInfo owner, ISymbol symbol, uint id, uint setterId, ulong resultObjectId,
            int maximumUtf8Bytes, int maximumCollectionCount, MemberShape shape, ITypeSymbol? resultType)
        {
            Owner = owner;
            Symbol = symbol;
            Id = id;
            SetterId = setterId;
            ResultObjectId = resultObjectId;
            MaximumUtf8Bytes = maximumUtf8Bytes;
            MaximumCollectionCount = maximumCollectionCount;
            Shape = shape;
            ResultType = resultType;
        }

        internal ObjectInfo Owner { get; }
        internal ISymbol Symbol { get; }
        internal uint Id { get; }
        internal uint SetterId { get; }
        internal ulong ResultObjectId { get; }
        internal int MaximumUtf8Bytes { get; }
        internal int MaximumCollectionCount { get; }
        internal MemberShape Shape { get; }
        internal ITypeSymbol? ResultType { get; }
    }

    private sealed class ContractInfo
    {
        internal ContractInfo(INamedTypeSymbol root, string @namespace, string contractId, int majorVersion, int minorVersion,
            string interfaceId, ObjectInfo rootObject, ObjectInfo collectionObject, ObjectInfo child, MemberInfo add,
            MemberInfo collection, MemberInfo count, MemberInfo getAt, List<MemberInfo> childStrings, MemberInfo initialProperty)
        {
            Root = root;
            Namespace = @namespace;
            ContractId = contractId;
            MajorVersion = majorVersion;
            MinorVersion = minorVersion;
            InterfaceId = interfaceId;
            RootObject = rootObject;
            CollectionObject = collectionObject;
            Child = child;
            Add = add;
            Collection = collection;
            Count = count;
            GetAt = getAt;
            ChildStrings = childStrings;
            InitialProperty = initialProperty;
            Objects = [rootObject, collectionObject, child];
        }

        internal INamedTypeSymbol Root { get; }
        internal string Namespace { get; }
        internal string ContractId { get; }
        internal int MajorVersion { get; }
        internal int MinorVersion { get; }
        internal string InterfaceId { get; }
        internal ObjectInfo RootObject { get; }
        internal ObjectInfo CollectionObject { get; }
        internal ObjectInfo Child { get; }
        internal MemberInfo Add { get; }
        internal MemberInfo Collection { get; }
        internal MemberInfo Count { get; }
        internal MemberInfo GetAt { get; }
        internal List<MemberInfo> ChildStrings { get; }
        internal MemberInfo InitialProperty { get; }
        internal List<ObjectInfo> Objects { get; }
    }

    private enum MemberShape
    {
        StringProperty = 1,
        CollectionProperty = 2,
        CountProperty = 3,
        StringToObjectMethod = 4,
        IntToObjectMethod = 5,
    }
}
