using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Devolutions.MultiPwsh.LiveContract.Generator;

[Generator]
public sealed class LiveContractGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> declarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.InterfaceDeclarationSyntax { AttributeLists.Count: > 0 },
                static (syntax, _) => (INamedTypeSymbol)syntax.SemanticModel.GetDeclaredSymbol(syntax.Node)!)
            .Where(static type => HasAttribute(type, "LiveContractAttribute") || HasAttribute(type, "LiveObjectAttribute"));

        IncrementalValueProvider<string> mode = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => options.GlobalOptions.TryGetValue("build_property.LiveContractMode", out string? value) ? value : string.Empty);

        context.RegisterSourceOutput(declarations.Collect().Combine(mode), static (production, pair) =>
        {
            if (pair.Right is not ("Host" or "Payload"))
            {
                production.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("MPWLC001", "Live contract mode is required",
                        "Set LiveContractMode to Host or Payload when compiling a [LiveContract] declaration.",
                        "LiveContract", DiagnosticSeverity.Error, true),
                    Location.None));
                return;
            }

            INamedTypeSymbol? root = pair.Left.FirstOrDefault(static type => HasAttribute(type, "LiveContractAttribute"));
            if (root is null)
            {
                return;
            }

            AttributeData contract = GetAttribute(root, "LiveContractAttribute")!;
            if (contract.ConstructorArguments.Length != 3 ||
                contract.ConstructorArguments[0].Value is not string contractId ||
                contract.ConstructorArguments[1].Value is not int major ||
                contract.ConstructorArguments[2].Value is not int minor)
            {
                production.ReportDiagnostic(Diagnostic.Create(InvalidContract, root.Locations[0], root.Name));
                return;
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace Devolutions.MultiPwsh.LiveContracts;");
            source.Append("internal static class ").Append(root.Name).AppendLine("Generated");
            source.AppendLine("{");
            source.Append("    internal const string ContractId = \"").Append(contractId).AppendLine("\";");
            source.Append("    internal const int MajorVersion = ").Append(major).AppendLine(";");
            source.Append("    internal const int MinorVersion = ").Append(minor).AppendLine(";");
            source.Append("    internal const uint ContractHash = 0x").Append(Fnv1a(contractId + ":" + major + ":" + minor).ToString("X8")).AppendLine(";");
            source.Append("    internal const string Mode = \"").Append(pair.Right).AppendLine("\";");

            foreach (INamedTypeSymbol type in pair.Left.Where(static type => HasAttribute(type, "LiveObjectAttribute")).OrderBy(static type => type.Name))
            {
                AttributeData objectAttribute = GetAttribute(type, "LiveObjectAttribute")!;
                if (objectAttribute.ConstructorArguments[0].Value is not ulong objectId)
                {
                    production.ReportDiagnostic(Diagnostic.Create(InvalidContract, type.Locations[0], type.Name));
                    continue;
                }

                string objectName = type.Equals(root, SymbolEqualityComparer.Default)
                    ? "RootObjectId"
                    : type.Name.Contains("Children", StringComparison.Ordinal)
                        ? "ChildrenObjectId"
                        : type.Name.Replace("I", string.Empty) + "ObjectId";
                source.Append("    internal const ulong ").Append(objectName).Append(" = ").Append(objectId).AppendLine("UL;");
                foreach (ISymbol member in type.GetMembers())
                {
                    AttributeData? memberAttribute = GetAttribute(member, "LiveMemberAttribute");
                    if (memberAttribute is null)
                    {
                        continue;
                    }

                    if (memberAttribute.ConstructorArguments[0].Value is not uint memberId)
                    {
                        production.ReportDiagnostic(Diagnostic.Create(InvalidMember, member.Locations[0], member.Name));
                        continue;
                    }

                    string baseName = type.Equals(root, SymbolEqualityComparer.Default)
                        ? member.Name
                        : member.Name;
                    if (member is IPropertySymbol property)
                    {
                        source.Append("    internal const uint ").Append(baseName).Append("Get = ").Append(memberId).AppendLine("U;");
                        uint setter = GetNamedUInt(memberAttribute, "SetterId");
                        if (property.SetMethod is not null && setter == 0)
                        {
                            production.ReportDiagnostic(Diagnostic.Create(MissingSetterId, member.Locations[0], member.Name));
                        }
                        else if (setter != 0)
                        {
                            source.Append("    internal const uint ").Append(baseName).Append("Set = ").Append(setter).AppendLine("U;");
                        }
                    }
                    else
                    {
                        source.Append("    internal const uint ").Append(baseName).Append(" = ").Append(memberId).AppendLine("U;");
                    }
                }
            }

            source.AppendLine("}");
            production.AddSource($"{root.Name}.{pair.Right}.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }

    private static readonly DiagnosticDescriptor InvalidContract = new(
        "MPWLC002", "Invalid live contract", "Live contract '{0}' must declare a stable ID and major/minor version.", "LiveContract", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor InvalidMember = new(
        "MPWLC003", "Invalid live member", "Live member '{0}' must declare an explicit non-zero member ID.", "LiveContract", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingSetterId = new(
        "MPWLC004", "Missing setter member ID", "Mutable live property '{0}' must declare SetterId.", "LiveContract", DiagnosticSeverity.Error, true);

    private static bool HasAttribute(ISymbol symbol, string name) => GetAttribute(symbol, name) is not null;
    private static AttributeData? GetAttribute(ISymbol symbol, string name) =>
        symbol.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.Name == name);
    private static uint GetNamedUInt(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value.Value is uint value ? value : 0;
    private static uint Fnv1a(string value)
    {
        uint hash = 2166136261;
        foreach (char character in value)
        {
            hash ^= character;
            hash *= 16777619;
        }
        return hash;
    }
}
