param(
    [Parameter(Mandatory = $false)]
    [string]$ContractPath = "$PSScriptRoot/../dotnet/bindings/obj/bindings.ps74.discovered.contract.json",

    [Parameter(Mandatory = $false)]
    [string]$CSharpOutputPath = "$PSScriptRoot/../dotnet/bindings/Bindings.Generated.cs",

    [Parameter(Mandatory = $false)]
    [string]$RustOutputPath = "$PSScriptRoot/../crates/pwsh-host/src/bindings/bindings_generated.rs"
)

$ErrorActionPreference = "Stop"

$contract = Get-Content -Raw -Path $ContractPath | ConvertFrom-Json
$entries = @($contract.entries)

if ($entries.Count -eq 0) {
    throw "No entries found in contract: $ContractPath"
}

$apiStructName = $contract.csharpApiStructName
$rustApiStructName = $contract.rustApiStructName
$bootstrapMethod = $contract.bootstrapMethod
$bindingTypeName = $contract.bindingTypeName
$rustGetApiFunctionType = $contract.rustGetApiFunctionType

$csharpFields = ($entries | ForEach-Object { "            public IntPtr $($_.tableField);" }) -join "`n"
$csharpAssign = ($entries | ForEach-Object { "                $($_.tableField) = (IntPtr)($($_.csharpFunctionPointer))&$($_.name)," }) -join "`n"

$rustTypedefs = ($entries | ForEach-Object {
    "pub type $($_.rustTypedef) = $($_.rustSignature);"
}) -join "`n`n"

$rustApiFields = ($entries | ForEach-Object { "    pub $($_.rustField): *const libc::c_void," }) -join "`n"
$rustBindingFields = ($entries | ForEach-Object { "    pub $($_.rustField): $($_.rustTypedef)," }) -join "`n"
$rustTransmutes = ($entries | ForEach-Object { "            $($_.rustField): unsafe { std::mem::transmute(api.$($_.rustField)) }," }) -join "`n"

$csharpContent = @"
// <auto-generated />
using System;
using System.Runtime.InteropServices;

namespace NativeHost
{
    public static partial class Bindings
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct $apiStructName
        {
$csharpFields
        }

        private static readonly object ${apiStructName}Lock = new object();
        private static IntPtr ${apiStructName}Ptr = IntPtr.Zero;

        [UnmanagedCallersOnly]
        public static IntPtr $bootstrapMethod()
        {
            lock (${apiStructName}Lock)
            {
                if (${apiStructName}Ptr == IntPtr.Zero)
                {
                    $apiStructName api = Create$apiStructName();
                    ${apiStructName}Ptr = Marshal.AllocCoTaskMem(Marshal.SizeOf<$apiStructName>());
                    Marshal.StructureToPtr(api, ${apiStructName}Ptr, false);
                }

                return ${apiStructName}Ptr;
            }
        }

        private static unsafe $apiStructName Create$apiStructName()
        {
            return new $apiStructName
            {
$csharpAssign
            };
        }
    }
}
"@

$rustContent = @"
// <auto-generated />
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use crate::delegate_loader::{AssemblyDelegateLoader, MethodWithUnknownSignature};
use crate::error::Error;
use crate::loader::get_assembly_delegate_loader;
use crate::pdcstr;
use crate::pdcstring::{PdCStr, PdCString};

pub type PowerShellHandle = *mut libc::c_void;

$rustTypedefs

#[repr(C)]
#[derive(Clone, Copy)]
pub struct $rustApiStructName {
$rustApiFields
}

pub type $rustGetApiFunctionType = unsafe extern "system" fn() -> *const $rustApiStructName;

pub type FnBindingsGetAbiVersion = unsafe extern "system" fn() -> i32;

#[derive(Clone, Copy)]
pub struct Bindings {
$rustBindingFields
}

impl Bindings {
    pub fn new() -> Result<Self, Error> {
        let fn_loader = get_assembly_delegate_loader();
        Self::new_with_loader(&fn_loader)
    }

    pub fn new_with_loader(fn_loader: &AssemblyDelegateLoader<PdCString>) -> Result<Self, Error> {
        fn get_function_pointer(
            fn_loader: &AssemblyDelegateLoader<PdCString>,
            type_name: impl AsRef<PdCStr>,
            method_name: impl AsRef<PdCStr>,
        ) -> Result<MethodWithUnknownSignature, Error> {
            fn_loader.get_function_pointer_for_unmanaged_callers_only_method(type_name, method_name)
        }

        let get_api_fn: $rustGetApiFunctionType = {
            let fn_ptr = get_function_pointer(
                fn_loader,
                pdcstr!("$bindingTypeName"),
                pdcstr!("$bootstrapMethod"),
            )?;
            unsafe { std::mem::transmute(fn_ptr) }
        };

        let get_abi_version_fn: FnBindingsGetAbiVersion = {
            let fn_ptr = get_function_pointer(
                fn_loader,
                pdcstr!("$bindingTypeName"),
                pdcstr!("Bindings_GetAbiVersion"),
            )?;
            unsafe { std::mem::transmute(fn_ptr) }
        };
        if unsafe { get_abi_version_fn() } != 2 {
            return Err(Error::IO(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "unsupported managed PowerShell bindings ABI version",
            )));
        }

        let api = unsafe {
            let api_ptr = get_api_fn();
            assert!(!api_ptr.is_null());
            *api_ptr
        };

        Ok(Self {
$rustTransmutes
        })
    }
}
"@

$resolvedCSharpOutputPath = [System.IO.Path]::GetFullPath($CSharpOutputPath)
$resolvedRustOutputPath = [System.IO.Path]::GetFullPath($RustOutputPath)

$csharpDirectory = Split-Path -Parent $resolvedCSharpOutputPath
$rustDirectory = Split-Path -Parent $resolvedRustOutputPath

if (-not (Test-Path -Path $csharpDirectory)) {
    New-Item -Path $csharpDirectory -ItemType Directory -Force | Out-Null
}

if (-not (Test-Path -Path $rustDirectory)) {
    New-Item -Path $rustDirectory -ItemType Directory -Force | Out-Null
}

Set-Content -Path $resolvedCSharpOutputPath -Value $csharpContent -Encoding UTF8
Set-Content -Path $resolvedRustOutputPath -Value $rustContent -Encoding UTF8

$rustfmtCommand = Get-Command rustfmt -ErrorAction SilentlyContinue
if ($null -ne $rustfmtCommand) {
    & $rustfmtCommand.Source --edition 2018 $resolvedRustOutputPath
    if ($LASTEXITCODE -ne 0) {
        throw "rustfmt failed for generated Rust bindings: $resolvedRustOutputPath"
    }
}
else {
    Write-Warning "rustfmt not found; generated Rust bindings may require formatting."
}

Write-Output "Generated: $resolvedCSharpOutputPath"
Write-Output "Generated: $resolvedRustOutputPath"
